In [2]:
import pandas as pd

In [3]:
flights = pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Flights.csv")
passengers=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Passengers.csv")
routes=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Routes.csv")
airlines=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Airlines.csv")
airports=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Airports.csv")
staffs=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Staff.csv")
aircraft=pd.read_csv(r"C:\Users\Asus\Downloads\airline_duplicates\Aircraft.csv")

In [4]:
flights

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
0,FL00001,2023-03-02,AL002,AC013,AP013,AP027,2023-03-02 15:00:00,2023-03-02 15:11:00,11.0,Security,Delayed,647,1322,325,219,361.0,79059,67.384615,Spring
1,FL00002,2023-11-18,AL009,AC036,AP010,AP006,2023-11-18 22:30:00,2023-11-18 22:36:00,6.0,Technical,Delayed,603,5627,180,131,624.0,81744,72.777778,Autumn
2,FL00003,2025-02-05,AL002,AC019,AP022,AP009,2025-02-05 19:30:00,2025-02-05 19:30:00,0.0,NaN,On Time,262,2326,296,225,541.0,121725,76.013514,Winter
3,FL00004,2023-11-20,AL004,AC012,AP024,AP030,2023-11-20 13:00:00,2023-11-20 13:12:00,12.0,Late Aircraft,Delayed,354,1407,189,163,469.0,76447,86.243386,Autumn
4,FL00005,2025-03-30,AL003,AC023,AP023,AP016,2025-03-30 08:15:00,2025-03-30 08:25:00,10.0,Late Aircraft,Delayed,207,2646,180,178,214.0,38092,98.888889,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5025,FL04685,2024-04-05,AL008,AC034,AP027,AP012,2024-04-05 21:00:00,2024-04-05 21:14:00,14.0,Late Aircraft,Delayed,551,4111,300,191,642.0,122622,63.666667,Spring
5026,FL00290,2024-02-18,AL009,AC010,AP029,AP007,2024-02-18 17:00:00,2024-02-18 17:14:00,14.0,Late Aircraft,Delayed,429,3121,396,272,328.0,89216,68.686869,Winter
5027,FL02854,2025-02-10,AL001,AC001,AP020,AP008,2025-02-10 13:00:00,2025-02-10 13:12:00,12.0,Technical,Delayed,54,3635,325,257,622.0,159854,79.076923,Winter
5028,FL04476,2025-02-02,AL009,AC017,AP018,AP007,2025-02-02 09:45:00,2025-02-02 10:13:00,28.0,Late Aircraft,Delayed,161,4129,296,213,507.0,107991,71.959459,Winter
5029,FL02389,2025-12-13,AL010,AC035,AP011,AP012,2025-12-13 09:30:00,2025-12-13 09:41:00,11.0,Crew,Delayed,390,4785,189,125,583.0,72875,66.137566,Winter

In [5]:
flights[flights.duplicated(keep=False)].sort_values(by=list(flights.columns))

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
22,FL00023,2024-09-27,AL001,AC008,AP004,AP023,2024-09-27 07:15:00,2024-09-27 07:24:00,9.0,Technical,Delayed,609,5621,300,168,614.0,103152,56.000000,Autumn
5013,FL00023,2024-09-27,AL001,AC008,AP004,AP023,2024-09-27 07:15:00,2024-09-27 07:24:00,9.0,Technical,Delayed,609,5621,300,168,614.0,103152,56.000000,Autumn
33,FL00034,2024-09-01,AL007,AC034,AP024,AP007,2024-09-01 14:30:00,2024-09-01 16:18:00,108.0,Late Aircraft,Delayed,87,6682,300,217,149.0,32333,72.333333,Autumn
5010,FL00034,2024-09-01,AL007,AC034,AP024,AP007,2024-09-01 14:30:00,2024-09-01 16:18:00,108.0,Late Aircraft,Delayed,87,6682,300,217,149.0,32333,72.333333,Autumn
71,FL00072,2023-11-19,AL010,AC034,AP006,AP011,2023-11-19 13:30:00,2023-11-19 13:38:00,8.0,Air Traffic,Delayed,439,3086,300,200,269.0,53800,66.666667,Autumn
5015,FL00072,2023-11-19,AL010,AC034,AP006,AP011,2023-11-19 13:30:00,2023-11-19 13:38:00,8.0,Air Traffic,Delayed,439,3086,300,200,269.0,53800,66.666667,Autumn
265,FL00266,2024-12-14,AL010,AC001,AP023,AP015,2024-12-14 08:45:00,2024-12-14 08:45:00,0.0,NaN,On Time,468,2517,325,298,442.0,131716,91.692308,Winter
5005,FL00266,2024-12-14,AL010,AC001,AP023,AP015,2024-12-14 08:45:00,2024-12-14 08:45:00,0.0,NaN,On Time,468,2517,325,298,442.0,131716,91.692308,Winter
289,FL00290,2024-02-18,AL009,AC010,AP029,AP007,2024-02-18 17:00:00,2024-02-18 17:14:00,14.0,Late Aircraft,Delayed,429,3121,396,272,328.0,89216,68.686869,Winter
5026,FL00290,2024-02-18,AL009,AC010,AP029,AP007,2024-02-18 17:00:00,2024-02-18 17:14:00,14.0,Late Aircraft,Delayed,429,3121,396,272,328.0,89216,68.686869,Winter
525,FL00526,2023-06-25,AL010,AC026,AP028,AP005,2023-06-25 08:15:00,2023-06-25 08:20:00,NaN,Air Traffic,Delayed,379,3014,189,88,624.0,54912,46.560847,Summer
5001,FL00526,2023-06-25,AL010,AC026,AP028,AP005,2023-06-25 08:15:00,2023-06-25 08:20:00,NaN,Air Traffic,Delayed,379,3014,189,88,624.0,54912,46.560847,Summer
796,FL00797,2023-09-22,AL002,AC034,AP001,AP029,2023-09-22 09:30:00,2023-09-22 09:36:00,6.0,Air Traffic,Delayed,495,5649,300,260,371.0,96460,86.666667,Autumn
5017,FL00797,2023-09-22,AL002,AC034,AP001,AP029,2023-09-22 09:30:00,2023-09-22 09:36:00,6.0,Air Traffic,Delayed,495,5649,300,260,371.0,96460,86.666667,Autumn
849,FL00850,2025-05-02,AL001,AC030,AP022,AP004,2025-05-02 15:45:00,2025-05-02 16:23:00,38.0,Late Aircraft,Delayed,662,4704,325,297,467.0,138699,91.384615,Spring
5011,FL00850,2025-05-02,AL001,AC030,AP022,AP004,2025-05-02 15:45:00,2025-05-02 16:23:00,38.0,Late Aircraft,Delayed,662,4704,325,297,467.0,138699,91.384615,Spring
1021,FL01022,2023-06-11,AL007,AC003,AP001,AP021,2023-06-11 18:00:00,2023-06-11 18:10:00,10.0,Late Aircraft,Delayed,695,1162,396,295,179.0,52805,74.494949,Summer
5008,FL01022,2023-06-11,AL007,AC003,AP001,AP021,2023-06-11 18:00:00,2023-06-11 18:10:00,10.0,Late Aircraft,Delayed,695,1162,396,295,179.0,52805,74.494949,Summer
1024,FL01025,2023-03-18,AL003,AC027,AP006,AP023,2023-03-18 18:30:00,2023-03-18 18:34:00,4.0,Technical,Delayed,511,1959,325,264,590.0,155760,81.230769,Spring
5018,FL01025,2023-03-18,AL003,AC027,AP006,AP023,2023-03-18 18:30:00,2023-03-18 18:34:00,4.0,Technical,Delayed,511,1959,325,264,590.0,155760,81.230769,Spring
1517,FL01518,2025-05-27,AL002,AC008,AP015,AP018,2025-05-27 12:00:00,2025-05-27 15:00:00,180.0,Crew,Severely Delayed,276,3393,300,214,99.0,21186,71.333333,Spring
5016,FL01518,2025-05-27,AL002,AC008,AP015,AP018,2025-05-27 12:00:00,2025-05-27 15:00:00,180.0,Crew,Severely Delayed,276,3393,300,214,99.0,21186,71.333333,Spring
1716,FL01717,2025-02-21,AL001,AC040,AP006,AP017,2025-02-21 13:45:00,2025-02-21 13:47:00,2.0,Security,Delayed,150,397,220,162,239.0,38718,73.636364,Winter
5024,FL01717,2025-02-21,AL001,AC040,AP006,AP017,2025-02-21 13:45:00,2025-02-21 13:47:00,2.0,Security,Delayed,150,397,220,162,239.0,38718,73.636364,Winter
2031,FL02032,2023-04-29,AL007,AC032,AP018,AP003,2023-04-29 22:45:00,2023-04-29 23:00:00,15.0,Weather,Delayed,514,642,396,334,71.0,23714,84.343434,Spring
5007,FL02032,2023-04-29,AL007,AC032,AP018,AP003,2023-04-29 22:45:00,2023-04-29 23:00:00,15.0,Weather,Delayed,514,642,396,334,71.0,23714,84.343434,Spring
2104,FL02105,2023-12-11,AL003,AC039,AP028,AP001,2023-12-11 13:15:00,2023-12-11 13:25:00,10.0,Weather,Delayed,709,7395,300,233,NaN,84113,77.666667,Winter
5023,FL02105,2023-12-11,AL003,AC039,AP028,AP001,2023-12-11 13:15:00,2023-12-11 13:25:00,10.0,Weather,Delayed,709,7395,300,233,NaN,84113,77.666667,Winter
2388,FL02389,2025-12-13,AL010,AC035,AP011,AP012,2025-12-13 09:30:00,2025-12-13 09:41:00,11.0,Crew,Delayed,390,4785,189,125,583.0,72875,66.137566,Winter
5029,FL02389,2025-12-13,AL010,AC035,AP011,AP012,2025-12-13 09:30:00,2025-12-13 09:41:00,11.0,Crew,Delayed,390,4785,189,125,583.0,72875,66.137566,Winter
2567,FL02568,2024-02-28,AL002,AC008,AP029,AP015,2024-02-28 22:30:00,2024-02-28 22:35:00,5.0,Air Traffic,Delayed,139,5816,300,250,583.0,145750,83.333333,Winter
5012,FL02568,2024-02-28,AL002,AC008,AP029,AP015,2024-02-28 22:30:00,2024-02-28 22:35:00,5.0,Air Traffic,Delayed,139,5816,300,250,583.0,145750,83.333333,Winter
2600,FL02601,2024-11-22,AL003,AC014,AP010,AP002,2024-11-22 15:45:00,2024-11-22 17:36:00,111.0,Late Aircraft,Delayed,439,4457,325,216,174.0,37584,66.461538,Autumn
5006,FL02601,2024-11-22,AL003,AC014,AP010,AP002,2024-11-22 15:45:00,2024-11-22 17:36:00,111.0,Late Aircraft,Delayed,439,4457,325,216,174.0,37584,66.461538,Autumn
2853,FL02854,2025-02-10,AL001,AC001,AP020,AP008,2025-02-10 13:00:00,2025-02-10 13:12:00,12.0,Technical,Delayed,54,3635,325,257,622.0,159854,79.076923,Winter
5027,FL02854,2025-02-10,AL001,AC001,AP020,AP008,2025-02-10 13:00:00,2025-02-10 13:12:00,12.0,Technical,Delayed,54,3635,325,257,622.0,159854,79.076923,Winter
2973,FL02974,2024-08-08,AL008,AC038,AP008,AP006,2024-08-08 09:45:00,2024-08-08 09:50:00,5.0,Technical,Delayed,314,4878,189,122,421.0,51362,64.550265,Summer
5002,FL02974,2024-08-08,AL008,AC038,AP008,AP006,2024-08-08 09:45:00,2024-08-08 09:50:00,5.0,Technical,Delayed,314,4878,189,122,421.0,51362,64.550265,Summer
3183,FL03184,2025-03-27,AL009,AC002,AP023,AP021,2025-03-27 20:15:00,2025-03-27 20:16:00,1.0,Weather,Delayed,298,1087,300,251,134.0,33634,83.666667,Spring
5004,FL03184,2025-03-27,AL009,AC002,AP023,AP021,2025-03-27 20:15:00,2025-03-27 20:16:00,1.0,Weather,Delayed,298,1087,300,251,134.0,33634,83.666667,Spring
3220,FL03221,2025-04-05,AL005,AC004,AP019,AP015,2025-04-05 17:30:00,2025-04-05 19:43:00,133.0,Weather,Severely Delayed,59,6515,180,101,400.0,40400,56.111111,Spring
5014,FL03221,2025-04-05,AL005,AC004,AP019,AP015,2025-04-05 17:30:00,2025-04-05 19:43:00,133.0,Weather,Severely Delayed,59,6515,180,101,400.0,40400,56.111111,Spring
3230,FL03231,2024-07-10,AL006,AC024,AP004,AP013,2024-07-10 18:15:00,2024-07-10 18:20:00,5.0,Crew,Cancelled,497,2874,296,0,108.0,0,0.000000,Summer
5003,FL03231,2024-07-10,AL006,AC024,AP004,AP013,2024-07-10 18:15:00,2024-07-10 18:20:00,5.0,Crew,Cancelled,497,2874,296,0,108.0,0,0.000000,Summer
3310,FL03311,2025-10-06,AL004,AC038,AP025,AP009,2025-10-06 10:30:00,2025-10-06 13:00:00,150.0,Security,Severely Delayed,347,3731,189,167,233.0,38911,88.359788,Autumn
5009,FL03311,2025-10-06,AL004,AC038,AP025,AP009,2025-10-06 10:30:00,2025-10-06 13:00:00,150.0,Security,Severely Delayed,347,3731,189,167,233.0,38911,88.359788,Autumn
3605,FL03606,2025-01-14,AL002,AC004,AP017,AP014,2025-01-14 05:45:00,2025-01-14 05:45:00,0.0,NaN,On Time,274,1326,180,125,510.0,63750,69.444444,Winter
5020,FL03606,2025-01-14,AL002,AC004,AP017,AP014,2025-01-14 05:45:00,2025-01-14 05:45:00,0.0,NaN,On Time,274,1326,180,125,510.0,63750,69.444444,Winter
3829,FL03830,2024-12-04,AL005,AC016,AP015,AP029,2024-12-04 11:00:00,2024-12-04 13:14:00,134.0,Crew,Severely Delayed,84,7449,189,166,304.0,50464,87.830688,Winter
5019,FL03830,2024-12-04,AL005,AC016,AP015,AP029,2024-12-04 11:00:00,2024-12-04 13:14:00,134.0,Crew,Severely Delayed,84,7449,189,166,304.0,50464,87.830688,Winter
4475,FL04476,2025-02-02,AL009,AC017,AP018,AP007,2025-02-02 09:45:00,2025-02-02 10:13:00,28.0,Late Aircraft,Delayed,161,4129,296,213,507.0,107991,71.959459,Winter
5028,FL04476,2025-02-02,AL009,AC017,AP018,AP007,2025-02-02 09:45:00,2025-02-02 10:13:00,28.0,Late Aircraft,Delayed,161,4129,296,213,507.0,107991,71.959459,Winter
4572,FL04573,2023-01-16,AL008,AC034,AP024,AP014,2023-01-16 05:00:00,2023-01-16 05:09:00,9.0,Late Aircraft,Delayed,686,4194,300,249,363.0,90387,83.000000,Winter
5022,FL04573,2023-01-16,AL008,AC034,AP024,AP014,2023-01-16 05:00:00,2023-01-16 05:09:00,9.0,Late Aircraft,Delayed,686,4194,300,249,363.0,90387,83.000000,Winter
4684,FL04685,2024-04-05,AL008,AC034,AP027,AP012,2024-04-05 21:00:00,2024-04-05 21:14:00,14.0,Late Aircraft,Delayed,551,4111,300,191,642.0,122622,63.666667,Spring
5025,FL04685,2024-04-05,AL008,AC034,AP027,AP012,2024-04-05 21:00:00,2024-04-05 21:14:00,14.0,Late Aircraft,Delayed,551,4111,300,191,642.0,122622,63.666667,Spring
4704,FL04705,2024-12-06,AL010,AC006,AP027,AP004,2024-12-06 14:45:00,2024-12-06 14:52:00,7.0,Weather,Delayed,335,1253,300,289,265.0,76585,96.333333,Winter
5000,FL04705,2024-12-06,AL010,AC006,AP027,AP004,2024-12-06 14:45:00,2024-12-06 14:52:00,7.0,Weather,Delayed,335,1253,300,289,265.0,76585,96.333333,Winter
4745,FL04746,2025-10-01,AL002,AC018,AP030,AP027,2025-10-01 15:15:00,2025-10-01 17:47:00,152.0,Late Aircraft,Severely Delayed,118,7930,189,163,133.0,21679,86.243386,Autumn
5021,FL04746,2025-10-01,AL002,AC018,AP030,AP027,2025-10-01 15:15:00,2025-10-01 17:47:00,152.0,Late Aircraft,Severely Delayed,118,7930,189,163,133.0,21679,86.243386,Autumn

In [6]:
print(flights["Delay_Minutes"].head(10))

0     11.0
1      6.0
2      0.0
3     12.0
4     10.0
5     14.0
6      7.0
7    160.0
8      1.0
9      8.0
Name: Delay_Minutes, dtype: float64

In [7]:
print(flights["Delay_Minutes"].dtype)

float64

In [8]:
flights=flights.drop_duplicates()
flights

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
0,FL00001,2023-03-02,AL002,AC013,AP013,AP027,2023-03-02 15:00:00,2023-03-02 15:11:00,11.0,Security,Delayed,647,1322,325,219,361.0,79059,67.384615,Spring
1,FL00002,2023-11-18,AL009,AC036,AP010,AP006,2023-11-18 22:30:00,2023-11-18 22:36:00,6.0,Technical,Delayed,603,5627,180,131,624.0,81744,72.777778,Autumn
2,FL00003,2025-02-05,AL002,AC019,AP022,AP009,2025-02-05 19:30:00,2025-02-05 19:30:00,0.0,NaN,On Time,262,2326,296,225,541.0,121725,76.013514,Winter
3,FL00004,2023-11-20,AL004,AC012,AP024,AP030,2023-11-20 13:00:00,2023-11-20 13:12:00,12.0,Late Aircraft,Delayed,354,1407,189,163,469.0,76447,86.243386,Autumn
4,FL00005,2025-03-30,AL003,AC023,AP023,AP016,2025-03-30 08:15:00,2025-03-30 08:25:00,10.0,Late Aircraft,Delayed,207,2646,180,178,214.0,38092,98.888889,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,FL04996,2024-05-13,AL009,AC019,AP004,AP024,2024-05-13 08:30:00,2024-05-13 10:51:00,141.0,Air Traffic,Severely Delayed,557,4912,296,211,533.0,112463,71.283784,Spring
4996,FL04997,2023-05-19,AL002,AC036,AP017,AP009,2023-05-19 11:45:00,2023-05-19 12:00:00,15.0,Weather,Delayed,492,3561,180,131,279.0,36549,72.777778,Spring
4997,FL04998,2023-11-27,AL002,AC011,AP024,AP015,2023-11-27 17:15:00,2023-11-27 17:17:00,2.0,Air Traffic,Delayed,291,1483,300,288,396.0,114048,96.000000,Autumn
4998,FL04999,2025-02-13,AL008,AC039,AP018,AP013,2025-02-13 14:15:00,2025-02-13 14:21:00,6.0,Late Aircraft,Delayed,326,3218,300,227,496.0,112592,75.666667,Winter
4999,FL05000,2023-10-17,AL008,AC036,AP004,AP018,2023-10-17 13:00:00,2023-10-17 13:02:00,2.0,Crew,Delayed,465,3254,180,103,185.0,19055,57.222222,Autumn

In [9]:
flights.duplicated().sum()

np.int64(0)

In [10]:
flights[flights["Delay_Minutes"].isnull()]

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
169,FL00170,2023-12-28,AL009,AC032,AP012,AP006,2023-12-28 09:00:00,2023-12-28 09:02:00,NaN,Late Aircraft,Delayed,275,5632,396,312,377.0,117624,78.787879,Winter
172,FL00173,2024-03-18,AL001,AC025,AP002,AP023,2024-03-18 20:45:00,2024-03-18 20:47:00,NaN,Security,Delayed,488,5041,296,219,329.0,72051,73.986486,Spring
389,FL00390,2025-06-27,AL001,AC012,AP026,AP010,2025-06-27 15:00:00,2025-06-27 15:04:00,NaN,Crew,Delayed,606,4785,189,161,114.0,18354,85.185185,Summer
525,FL00526,2023-06-25,AL010,AC026,AP028,AP005,2023-06-25 08:15:00,2023-06-25 08:20:00,NaN,Air Traffic,Delayed,379,3014,189,88,624.0,54912,46.560847,Summer
772,FL00773,2024-12-22,AL006,AC024,AP017,AP026,2024-12-22 17:30:00,2024-12-22 17:38:00,NaN,Air Traffic,Delayed,229,4757,296,257,478.0,122846,86.824324,Winter
941,FL00942,2024-03-11,AL001,AC021,AP003,AP025,2024-03-11 07:00:00,2024-03-11 07:10:00,NaN,Weather,Delayed,276,2546,325,222,233.0,51726,68.307692,Spring
1133,FL01134,2024-09-27,AL001,AC037,AP022,AP013,2024-09-27 16:15:00,2024-09-27 16:26:00,NaN,Technical,Delayed,364,7797,220,150,372.0,55800,68.181818,Autumn
1300,FL01301,2024-01-01,AL003,AC017,AP007,AP012,2024-01-01 16:15:00,2024-01-01 18:04:00,NaN,Air Traffic,Delayed,272,5792,296,227,79.0,17933,76.689189,Winter
1559,FL01560,2024-11-17,AL006,AC020,AP022,AP014,2024-11-17 13:30:00,2024-11-17 13:44:00,NaN,Crew,Delayed,588,5729,396,261,491.0,128151,65.909091,Autumn
1585,FL01586,2025-05-07,AL008,AC006,AP008,AP002,2025-05-07 21:30:00,2025-05-07 21:36:00,NaN,Security,Delayed,193,1691,300,272,312.0,84864,90.666667,Spring
1790,FL01791,2023-11-06,AL010,AC007,AP011,AP029,2023-11-06 18:30:00,2023-11-06 18:33:00,NaN,Air Traffic,Delayed,107,5515,300,271,470.0,127370,90.333333,Autumn
1857,FL01858,2023-07-16,AL007,AC033,AP013,AP018,2023-07-16 22:30:00,2023-07-16 22:50:00,NaN,Technical,Delayed,401,8341,220,119,631.0,75089,54.090909,Summer
2028,FL02029,2025-06-25,AL008,AC018,AP016,AP011,2025-06-25 05:00:00,2025-06-25 05:07:00,NaN,Air Traffic,Delayed,698,8239,189,136,427.0,58072,71.957672,Summer
2046,FL02047,2025-05-15,AL006,AC020,AP015,AP004,2025-05-15 06:30:00,2025-05-15 06:37:00,NaN,Late Aircraft,Delayed,391,5729,396,318,137.0,43566,80.303030,Spring
2097,FL02098,2024-12-05,AL009,AC013,AP023,AP015,2024-12-05 21:00:00,2024-12-05 21:05:00,NaN,Technical,Delayed,318,7352,325,196,351.0,68796,60.307692,Winter
2128,FL02129,2024-01-07,AL002,AC001,AP004,AP022,2024-01-07 14:45:00,2024-01-07 14:52:00,NaN,Air Traffic,Delayed,632,4033,325,321,470.0,150870,98.769231,Winter
2248,FL02249,2023-11-05,AL008,AC030,AP010,AP002,2023-11-05 14:30:00,2023-11-05 14:30:00,NaN,NaN,On Time,639,1764,325,259,132.0,34188,79.692308,Autumn
2347,FL02348,2023-08-21,AL009,AC014,AP023,AP011,2023-08-21 22:45:00,2023-08-21 22:52:00,NaN,Weather,Delayed,581,1538,325,249,552.0,137448,76.615385,Summer
2353,FL02354,2025-09-19,AL004,AC019,AP014,AP002,2025-09-19 13:15:00,2025-09-19 13:15:00,NaN,NaN,On Time,78,990,296,256,430.0,110080,86.486486,Autumn
2454,FL02455,2025-04-04,AL001,AC035,AP001,AP014,2025-04-04 14:45:00,2025-04-04 14:51:00,NaN,Weather,Delayed,689,4336,189,156,449.0,70044,82.539683,Spring
2471,FL02472,2023-03-09,AL005,AC021,AP029,AP006,2023-03-09 14:00:00,2023-03-09 14:10:00,NaN,Weather,Delayed,484,6614,325,192,626.0,120192,59.076923,Spring
2687,FL02688,2023-10-29,AL010,AC030,AP029,AP015,2023-10-29 15:00:00,2023-10-29 15:01:00,NaN,Security,Delayed,318,5047,325,175,449.0,78575,53.846154,Autumn
2734,FL02735,2023-06-03,AL008,AC035,AP010,AP006,2023-06-03 10:00:00,2023-06-03 10:07:00,NaN,Technical,Delayed,93,6740,189,151,589.0,88939,79.894180,Summer
2885,FL02886,2025-01-10,AL008,AC003,AP004,AP012,2025-01-10 16:45:00,2025-01-10 16:57:00,NaN,Security,Delayed,366,6604,396,283,592.0,167536,71.464646,Winter
2888,FL02889,2023-09-03,AL010,AC021,AP003,AP017,2023-09-03 08:45:00,2023-09-03 10:26:00,NaN,Weather,Delayed,202,2384,325,213,364.0,77532,65.538462,Autumn
3100,FL03101,2024-11-15,AL002,AC023,AP018,AP011,2024-11-15 18:30:00,2024-11-15 20:38:00,NaN,Air Traffic,Severely Delayed,147,3255,180,172,560.0,96320,95.555556,Autumn
3121,FL03122,2025-12-04,AL005,AC024,AP008,AP019,2025-12-04 14:00:00,2025-12-04 14:10:00,NaN,Technical,Delayed,232,3260,296,232,486.0,112752,78.378378,Winter
3376,FL03377,2024-01-21,AL003,AC014,AP004,AP016,2024-01-21 19:45:00,2024-01-21 20:00:00,NaN,Technical,Delayed,376,5326,325,209,123.0,25707,64.307692,Winter
3457,FL03458,2023-06-22,AL001,AC029,AP004,AP008,2023-06-22 05:30:00,2023-06-22 06:02:00,NaN,Late Aircraft,Delayed,82,1233,220,172,303.0,52116,78.181818,Summer
3485,FL03486,2023-05-26,AL010,AC015,AP027,AP006,2023-05-26 06:45:00,2023-05-26 06:48:00,NaN,Security,Delayed,699,3356,396,320,230.0,73600,80.808081,Spring
3644,FL03645,2025-10-12,AL002,AC010,AP004,AP024,2025-10-12 19:00:00,2025-10-12 19:08:00,NaN,Technical,Delayed,450,1396,396,303,442.0,133926,76.515152,Autumn
3714,FL03715,2023-03-24,AL007,AC025,AP028,AP009,2023-03-24 21:45:00,2023-03-24 22:05:00,NaN,Security,Delayed,346,1085,296,203,465.0,94395,68.581081,Spring
3989,FL03990,2025-03-26,AL009,AC029,AP025,AP014,2025-03-26 20:45:00,2025-03-26 20:58:00,NaN,Weather,Delayed,295,4065,220,194,307.0,59558,88.181818,Spring
4274,FL04275,2025-09-26,AL003,AC005,AP010,AP029,2025-09-26 08:30:00,2025-09-26 08:44:00,NaN,Crew,Delayed,718,8257,325,224,591.0,132384,68.923077,Autumn
4848,FL04849,2024-12-31,AL006,AC012,AP018,AP001,2024-12-31 15:30:00,2024-12-31 15:40:00,NaN,Technical,Delayed,323,7365,189,106,565.0,59890,56.084656,Winter

In [11]:
flights[flights["Delay_Minutes"].isnull()][["Scheduled_Departure", "Actual_Departure", "Delay_Minutes"]]

      Scheduled_Departure     Actual_Departure  Delay_Minutes
169   2023-12-28 09:00:00  2023-12-28 09:02:00            NaN
172   2024-03-18 20:45:00  2024-03-18 20:47:00            NaN
389   2025-06-27 15:00:00  2025-06-27 15:04:00            NaN
525   2023-06-25 08:15:00  2023-06-25 08:20:00            NaN
772   2024-12-22 17:30:00  2024-12-22 17:38:00            NaN
941   2024-03-11 07:00:00  2024-03-11 07:10:00            NaN
1133  2024-09-27 16:15:00  2024-09-27 16:26:00            NaN
1300  2024-01-01 16:15:00  2024-01-01 18:04:00            NaN
1559  2024-11-17 13:30:00  2024-11-17 13:44:00            NaN
1585  2025-05-07 21:30:00  2025-05-07 21:36:00            NaN
1790  2023-11-06 18:30:00  2023-11-06 18:33:00            NaN
1857  2023-07-16 22:30:00  2023-07-16 22:50:00            NaN
2028  2025-06-25 05:00:00  2025-06-25 05:07:00            NaN
2046  2025-05-15 06:30:00  2025-05-15 06:37:00            NaN
2097  2024-12-05 21:00:00  2024-12-05 21:05:00            NaN
2128  2024-01-07 14:45:00  2024-01-07 14:52:00            NaN
2248  2023-11-05 14:30:00  2023-11-05 14:30:00            NaN
2347  2023-08-21 22:45:00  2023-08-21 22:52:00            NaN
2353  2025-09-19 13:15:00  2025-09-19 13:15:00            NaN
2454  2025-04-04 14:45:00  2025-04-04 14:51:00            NaN
2471  2023-03-09 14:00:00  2023-03-09 14:10:00            NaN
2687  2023-10-29 15:00:00  2023-10-29 15:01:00            NaN
2734  2023-06-03 10:00:00  2023-06-03 10:07:00            NaN
2885  2025-01-10 16:45:00  2025-01-10 16:57:00            NaN
2888  2023-09-03 08:45:00  2023-09-03 10:26:00            NaN
3100  2024-11-15 18:30:00  2024-11-15 20:38:00            NaN
3121  2025-12-04 14:00:00  2025-12-04 14:10:00            NaN
3376  2024-01-21 19:45:00  2024-01-21 20:00:00            NaN
3457  2023-06-22 05:30:00  2023-06-22 06:02:00            NaN
3485  2023-05-26 06:45:00  2023-05-26 06:48:00            NaN
3644  2025-10-12 19:00:00  2025-10-12 19:08:00            NaN
3714  2023-03-24 21:45:00  2023-03-24 22:05:00            NaN
3989  2025-03-26 20:45:00  2025-03-26 20:58:00            NaN
4274  2025-09-26 08:30:00  2025-09-26 08:44:00            NaN
4848  2024-12-31 15:30:00  2024-12-31 15:40:00            NaN

In [12]:
print(flights[["Scheduled_Departure", "Actual_Departure"]].head())
print(flights[["Scheduled_Departure", "Actual_Departure"]].dtypes)

   Scheduled_Departure     Actual_Departure
0  2023-03-02 15:00:00  2023-03-02 15:11:00
1  2023-11-18 22:30:00  2023-11-18 22:36:00
2  2025-02-05 19:30:00  2025-02-05 19:30:00
3  2023-11-20 13:00:00  2023-11-20 13:12:00
4  2025-03-30 08:15:00  2025-03-30 08:25:00
Scheduled_Departure    str
Actual_Departure       str
dtype: object

In [13]:
flights["Scheduled_Departure"]=pd.to_datetime(flights["Scheduled_Departure"])
flights["Actual_Departure"] = pd.to_datetime(flights["Actual_Departure"])

In [14]:
print(flights[["Scheduled_Departure", "Actual_Departure"]].head())
print(flights[["Scheduled_Departure", "Actual_Departure"]].dtypes)

  Scheduled_Departure    Actual_Departure
0 2023-03-02 15:00:00 2023-03-02 15:11:00
1 2023-11-18 22:30:00 2023-11-18 22:36:00
2 2025-02-05 19:30:00 2025-02-05 19:30:00
3 2023-11-20 13:00:00 2023-11-20 13:12:00
4 2025-03-30 08:15:00 2025-03-30 08:25:00
Scheduled_Departure    datetime64[us]
Actual_Departure       datetime64[us]
dtype: object

In [15]:
flights["Calculated_delay"]=(flights["Actual_Departure"]-flights["Scheduled_Departure"]).dt.total_seconds()/60

In [16]:
flights["Calculated_delay"]

0        11.0
1         6.0
2         0.0
3        12.0
4        10.0
        ...
4995    141.0
4996     15.0
4997      2.0
4998      6.0
4999      2.0
Name: Calculated_delay, Length: 5000, dtype: float64

In [17]:
flights["Delay_Minutes"]=flights["Delay_Minutes"].fillna(flights["Calculated_delay"])
flights["Delay_Minutes"]

0        11.0
1         6.0
2         0.0
3        12.0
4        10.0
        ...
4995    141.0
4996     15.0
4997      2.0
4998      6.0
4999      2.0
Name: Delay_Minutes, Length: 5000, dtype: float64

In [18]:
flights["Delay_Minutes"].isnull().sum()

np.int64(0)

In [19]:
flights[flights["Actual_Departure"].isnull()][
    ["Scheduled_Departure", "Delay_Minutes", "Actual_Departure"]
]

     Scheduled_Departure  Delay_Minutes Actual_Departure
131  2025-06-15 22:00:00           10.0              NaT
396  2025-08-15 20:45:00           14.0              NaT
490  2025-10-21 10:00:00            3.0              NaT
588  2023-03-04 16:15:00            1.0              NaT
730  2023-06-27 20:45:00           12.0              NaT
785  2024-03-24 13:15:00           11.0              NaT
825  2023-04-17 10:30:00            5.0              NaT
882  2024-03-22 06:15:00            9.0              NaT
887  2025-10-16 09:00:00           10.0              NaT
1131 2025-11-20 10:15:00            4.0              NaT
1388 2025-08-26 05:45:00           12.0              NaT
1408 2024-04-01 07:45:00            9.0              NaT
1485 2024-05-22 09:15:00          171.0              NaT
1692 2023-06-30 06:00:00            4.0              NaT
1763 2023-02-26 10:15:00           41.0              NaT
1814 2025-03-29 15:30:00          101.0              NaT
1840 2024-08-10 16:45:00           83.0              NaT
2239 2025-05-13 06:15:00           10.0              NaT
2298 2025-01-17 07:00:00           15.0              NaT
2320 2025-08-18 12:15:00           12.0              NaT
2570 2024-10-26 22:45:00            5.0              NaT
3013 2025-06-24 08:00:00          166.0              NaT
3170 2023-10-03 22:15:00            5.0              NaT
3176 2024-05-08 05:15:00            9.0              NaT
3197 2023-02-16 14:15:00           13.0              NaT
3216 2024-01-22 22:45:00            3.0              NaT
3249 2025-01-06 21:30:00            5.0              NaT
3275 2025-11-24 16:00:00           13.0              NaT
3503 2024-08-30 21:45:00          135.0              NaT
3588 2024-12-07 16:30:00            8.0              NaT
3627 2023-04-19 06:00:00          175.0              NaT
3754 2025-05-23 18:15:00           10.0              NaT
3930 2025-03-06 08:15:00           12.0              NaT
4122 2025-06-14 05:30:00            6.0              NaT
4131 2024-06-06 10:15:00            2.0              NaT
4226 2023-05-17 05:15:00           11.0              NaT
4272 2024-06-16 16:30:00            1.0              NaT
4502 2025-04-15 06:30:00            7.0              NaT
4584 2025-07-04 21:00:00           25.0              NaT
4817 2024-09-24 18:00:00           12.0              NaT

In [20]:
flights["Actual_Departure"] = pd.to_datetime(flights["Actual_Departure"])
flights["Actual_Departure"]

0      2023-03-02 15:11:00
1      2023-11-18 22:36:00
2      2025-02-05 19:30:00
3      2023-11-20 13:12:00
4      2025-03-30 08:25:00
               ...
4995   2024-05-13 10:51:00
4996   2023-05-19 12:00:00
4997   2023-11-27 17:17:00
4998   2025-02-13 14:21:00
4999   2023-10-17 13:02:00
Name: Actual_Departure, Length: 5000, dtype: datetime64[us]

In [21]:
flights["Calculated_Actual_Departure"] = (
    flights["Scheduled_Departure"] +
    pd.to_timedelta(flights["Delay_Minutes"], unit="m")
)
flights["Calculated_Actual_Departure"]

0      2023-03-02 15:11:00
1      2023-11-18 22:36:00
2      2025-02-05 19:30:00
3      2023-11-20 13:12:00
4      2025-03-30 08:25:00
               ...
4995   2024-05-13 10:51:00
4996   2023-05-19 12:00:00
4997   2023-11-27 17:17:00
4998   2025-02-13 14:21:00
4999   2023-10-17 13:02:00
Name: Calculated_Actual_Departure, Length: 5000, dtype: datetime64[us]

In [22]:
flights[flights["Actual_Departure"].isnull()][
    ["Scheduled_Departure", "Delay_Minutes", "Calculated_Actual_Departure"]
]

     Scheduled_Departure  Delay_Minutes Calculated_Actual_Departure
131  2025-06-15 22:00:00           10.0         2025-06-15 22:10:00
396  2025-08-15 20:45:00           14.0         2025-08-15 20:59:00
490  2025-10-21 10:00:00            3.0         2025-10-21 10:03:00
588  2023-03-04 16:15:00            1.0         2023-03-04 16:16:00
730  2023-06-27 20:45:00           12.0         2023-06-27 20:57:00
785  2024-03-24 13:15:00           11.0         2024-03-24 13:26:00
825  2023-04-17 10:30:00            5.0         2023-04-17 10:35:00
882  2024-03-22 06:15:00            9.0         2024-03-22 06:24:00
887  2025-10-16 09:00:00           10.0         2025-10-16 09:10:00
1131 2025-11-20 10:15:00            4.0         2025-11-20 10:19:00
1388 2025-08-26 05:45:00           12.0         2025-08-26 05:57:00
1408 2024-04-01 07:45:00            9.0         2024-04-01 07:54:00
1485 2024-05-22 09:15:00          171.0         2024-05-22 12:06:00
1692 2023-06-30 06:00:00            4.0         2023-06-30 06:04:00
1763 2023-02-26 10:15:00           41.0         2023-02-26 10:56:00
1814 2025-03-29 15:30:00          101.0         2025-03-29 17:11:00
1840 2024-08-10 16:45:00           83.0         2024-08-10 18:08:00
2239 2025-05-13 06:15:00           10.0         2025-05-13 06:25:00
2298 2025-01-17 07:00:00           15.0         2025-01-17 07:15:00
2320 2025-08-18 12:15:00           12.0         2025-08-18 12:27:00
2570 2024-10-26 22:45:00            5.0         2024-10-26 22:50:00
3013 2025-06-24 08:00:00          166.0         2025-06-24 10:46:00
3170 2023-10-03 22:15:00            5.0         2023-10-03 22:20:00
3176 2024-05-08 05:15:00            9.0         2024-05-08 05:24:00
3197 2023-02-16 14:15:00           13.0         2023-02-16 14:28:00
3216 2024-01-22 22:45:00            3.0         2024-01-22 22:48:00
3249 2025-01-06 21:30:00            5.0         2025-01-06 21:35:00
3275 2025-11-24 16:00:00           13.0         2025-11-24 16:13:00
3503 2024-08-30 21:45:00          135.0         2024-08-31 00:00:00
3588 2024-12-07 16:30:00            8.0         2024-12-07 16:38:00
3627 2023-04-19 06:00:00          175.0         2023-04-19 08:55:00
3754 2025-05-23 18:15:00           10.0         2025-05-23 18:25:00
3930 2025-03-06 08:15:00           12.0         2025-03-06 08:27:00
4122 2025-06-14 05:30:00            6.0         2025-06-14 05:36:00
4131 2024-06-06 10:15:00            2.0         2024-06-06 10:17:00
4226 2023-05-17 05:15:00           11.0         2023-05-17 05:26:00
4272 2024-06-16 16:30:00            1.0         2024-06-16 16:31:00
4502 2025-04-15 06:30:00            7.0         2025-04-15 06:37:00
4584 2025-07-04 21:00:00           25.0         2025-07-04 21:25:00
4817 2024-09-24 18:00:00           12.0         2024-09-24 18:12:00

In [23]:
flights["Actual_Departure"] = flights["Actual_Departure"].fillna(flights["Calculated_Actual_Departure"])
flights["Actual_Departure"]

0      2023-03-02 15:11:00
1      2023-11-18 22:36:00
2      2025-02-05 19:30:00
3      2023-11-20 13:12:00
4      2025-03-30 08:25:00
               ...
4995   2024-05-13 10:51:00
4996   2023-05-19 12:00:00
4997   2023-11-27 17:17:00
4998   2025-02-13 14:21:00
4999   2023-10-17 13:02:00
Name: Actual_Departure, Length: 5000, dtype: datetime64[us]

In [24]:
flights["Actual_Departure"].isnull().sum()

np.int64(0)

In [25]:
flights.isnull().sum()

Flight_ID                        0
Flight_Date                      0
Airline_ID                       0
Aircraft_ID                      0
Origin_Airport_ID                0
Destination_Airport_ID           0
Scheduled_Departure              0
Actual_Departure                 0
Delay_Minutes                    0
Delay_Reason                   294
Status                           0
Flight_Duration_Min              0
Distance_KM                      0
Seat_Capacity                    0
Passengers                       0
Base_Fare_USD                   35
Revenue_USD                      0
Load_Factor_%                    0
Season                           0
Calculated_delay                40
Calculated_Actual_Departure      0
dtype: int64

In [26]:
flights.drop(columns=["Calculated_delay"], inplace=True)

In [27]:
flights.drop(columns=["Calculated_Actual_Departure"], inplace=True)

In [28]:
flights.isnull().sum()

Flight_ID                   0
Flight_Date                 0
Airline_ID                  0
Aircraft_ID                 0
Origin_Airport_ID           0
Destination_Airport_ID      0
Scheduled_Departure         0
Actual_Departure            0
Delay_Minutes               0
Delay_Reason              294
Status                      0
Flight_Duration_Min         0
Distance_KM                 0
Seat_Capacity               0
Passengers                  0
Base_Fare_USD              35
Revenue_USD                 0
Load_Factor_%               0
Season                      0
dtype: int64

In [29]:
flights[flights["Delay_Reason"].isnull()][["Delay_Minutes", "Delay_Reason"]]

      Delay_Minutes Delay_Reason
2               0.0          NaN
47              0.0          NaN
62             11.0          NaN
66              0.0          NaN
68              0.0          NaN
...             ...          ...
4935            0.0          NaN
4948            0.0          NaN
4954            0.0          NaN
4981            0.0          NaN
4994            0.0          NaN

[294 rows x 2 columns]

In [30]:
flights[flights["Delay_Reason"].isnull()]["Delay_Minutes"].describe()

count    294.000000
mean       1.666667
std       10.938758
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max      164.000000
Name: Delay_Minutes, dtype: float64

In [31]:
(flights["Delay_Reason"].isnull() & 
 (flights["Delay_Minutes"] == 0)).sum()

np.int64(264)

In [32]:
(flights["Delay_Reason"].isnull() & 
 (flights["Delay_Minutes"] > 0)).sum()

np.int64(30)

In [33]:
flights[
    (flights["Delay_Minutes"] > 0) &
    (flights["Delay_Reason"].isnull())
]

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
62,FL00063,2025-06-19,AL001,AC037,AP009,AP018,2025-06-19 11:15:00,2025-06-19 11:26:00,11.0,NaN,Delayed,520,1584,220,129,219.0,28251,58.636364,Summer
120,FL00121,2023-05-30,AL005,AC007,AP010,AP003,2023-05-30 16:15:00,2023-05-30 16:25:00,10.0,NaN,Delayed,105,4508,300,262,586.0,153532,87.333333,Spring
187,FL00188,2024-01-13,AL009,AC012,AP012,AP008,2024-01-13 07:00:00,2024-01-13 07:11:00,11.0,NaN,Delayed,161,797,189,139,233.0,32387,73.544974,Winter
299,FL00300,2024-03-31,AL005,AC031,AP011,AP028,2024-03-31 09:00:00,2024-03-31 09:05:00,5.0,NaN,Delayed,126,2115,300,257,372.0,95604,85.666667,Spring
431,FL00432,2025-11-19,AL005,AC005,AP012,AP003,2025-11-19 17:30:00,2025-11-19 20:14:00,164.0,NaN,Severely Delayed,526,4852,325,311,89.0,27679,95.692308,Autumn
462,FL00463,2023-03-01,AL010,AC038,AP016,AP010,2023-03-01 22:15:00,2023-03-01 22:20:00,5.0,NaN,Delayed,198,7987,189,134,541.0,72494,70.899471,Spring
510,FL00511,2024-12-30,AL010,AC007,AP020,AP004,2024-12-30 22:45:00,2024-12-30 22:51:00,6.0,NaN,Delayed,224,5437,300,264,444.0,117216,88.000000,Winter
524,FL00525,2025-08-08,AL002,AC014,AP019,AP001,2025-08-08 11:15:00,2025-08-08 11:16:00,1.0,NaN,Delayed,460,5888,325,205,632.0,129560,63.076923,Summer
797,FL00798,2024-01-29,AL003,AC039,AP009,AP016,2024-01-29 08:15:00,2024-01-29 08:43:00,28.0,NaN,Delayed,564,2603,300,205,82.0,16810,68.333333,Winter
1349,FL01350,2023-04-24,AL008,AC004,AP002,AP005,2023-04-24 09:00:00,2023-04-24 09:04:00,4.0,NaN,Delayed,210,7466,180,135,95.0,12825,75.000000,Spring
1406,FL01407,2025-01-23,AL010,AC007,AP012,AP004,2025-01-23 07:45:00,2025-01-23 07:54:00,9.0,NaN,Delayed,652,4903,300,214,152.0,32528,71.333333,Winter
1488,FL01489,2024-07-09,AL004,AC039,AP017,AP018,2024-07-09 20:30:00,2024-07-09 20:35:00,5.0,NaN,Delayed,208,2550,300,196,488.0,95648,65.333333,Summer
1489,FL01490,2025-07-15,AL007,AC003,AP008,AP013,2025-07-15 05:30:00,2025-07-15 05:40:00,10.0,NaN,Delayed,91,3785,396,262,380.0,99560,66.161616,Summer
1804,FL01805,2025-05-24,AL003,AC040,AP002,AP024,2025-05-24 11:15:00,2025-05-24 11:25:00,10.0,NaN,Delayed,563,3190,220,176,257.0,45232,80.000000,Spring
2336,FL02337,2025-03-24,AL009,AC003,AP021,AP015,2025-03-24 22:45:00,2025-03-24 22:55:00,10.0,NaN,Delayed,700,3691,396,305,202.0,61610,77.020202,Spring
2439,FL02440,2024-05-27,AL006,AC035,AP013,AP018,2024-05-27 07:15:00,2024-05-27 07:28:00,13.0,NaN,Delayed,457,1571,189,187,635.0,118745,98.941799,Spring
2464,FL02465,2024-08-07,AL003,AC025,AP003,AP019,2024-08-07 07:15:00,2024-08-07 07:28:00,13.0,NaN,Delayed,689,7658,296,244,585.0,142740,82.432432,Summer
2787,FL02788,2023-12-13,AL009,AC017,AP017,AP026,2023-12-13 18:45:00,2023-12-13 18:47:00,2.0,NaN,Delayed,289,7895,296,198,296.0,58608,66.891892,Winter
2828,FL02829,2024-10-12,AL006,AC026,AP014,AP010,2024-10-12 09:15:00,2024-10-12 09:16:00,1.0,NaN,Delayed,135,6903,189,141,543.0,76563,74.603175,Autumn
3017,FL03018,2024-03-03,AL010,AC040,AP028,AP023,2024-03-03 06:45:00,2024-03-03 07:00:00,15.0,NaN,Delayed,346,5737,220,93,NaN,17484,42.272727,Spring
3030,FL03031,2025-04-26,AL006,AC019,AP001,AP015,2025-04-26 11:00:00,2025-04-26 11:15:00,15.0,NaN,Delayed,691,7740,296,248,126.0,31248,83.783784,Spring
3096,FL03097,2025-03-05,AL002,AC014,AP012,AP010,2025-03-05 17:45:00,2025-03-05 17:56:00,11.0,NaN,Delayed,278,5111,325,302,648.0,195696,92.923077,Spring
3352,FL03353,2023-09-25,AL010,AC038,AP021,AP005,2023-09-25 14:30:00,2023-09-25 15:46:00,76.0,NaN,Delayed,681,4776,189,116,621.0,72036,61.375661,Autumn
4242,FL04243,2025-08-13,AL008,AC021,AP028,AP030,2025-08-13 06:00:00,2025-08-13 06:13:00,13.0,NaN,Delayed,110,3589,325,250,114.0,28500,76.923077,Summer
4410,FL04411,2023-04-12,AL005,AC012,AP029,AP019,2023-04-12 21:15:00,2023-04-12 21:30:00,15.0,NaN,Delayed,219,6938,189,130,549.0,71370,68.783069,Spring
4661,FL04662,2023-05-26,AL005,AC032,AP016,AP009,2023-05-26 20:45:00,2023-05-26 20:46:00,1.0,NaN,Delayed,50,6117,396,266,217.0,57722,67.171717,Spring
4702,FL04703,2025-06-27,AL003,AC016,AP003,AP009,2025-06-27 10:30:00,2025-06-27 10:33:00,3.0,NaN,Delayed,714,4468,189,146,NaN,18396,77.248677,Summer
4713,FL04714,2023-07-19,AL006,AC008,AP006,AP008,2023-07-19 11:30:00,2023-07-19 11:39:00,9.0,NaN,Delayed,425,1287,300,240,300.0,72000,80.000000,Summer
4776,FL04777,2024-07-25,AL009,AC011,AP006,AP011,2024-07-25 06:15:00,2024-07-25 06:16:00,1.0,NaN,Delayed,126,6566,300,177,427.0,75579,59.000000,Summer
4878,FL04879,2025-09-10,AL008,AC036,AP001,AP019,2025-09-10 22:15:00,2025-09-10 22:28:00,13.0,NaN,Delayed,238,5827,180,159,202.0,32118,88.333333,Autumn

In [34]:
flights[
    (flights["Delay_Minutes"] > 0) &
    (flights["Delay_Reason"].notnull())
].groupby("Delay_Minutes")["Delay_Reason"].value_counts()

Delay_Minutes  Delay_Reason
1.0            Security         63
               Air Traffic      46
               Weather          45
               Technical        44
               Crew             38
                                ..
179.0          Air Traffic       1
180.0          Technical         3
               Crew              2
               Security          1
               Late Aircraft     1
Name: count, Length: 735, dtype: int64

In [35]:
flights.loc[
    flights["Delay_Reason"].isnull() &
    (flights["Delay_Minutes"] == 0),
    "Delay_Reason"
] = "No Delay"

In [36]:
flights.loc[
    flights["Delay_Reason"].isnull() &
    (flights["Delay_Minutes"] > 0),
    "Delay_Reason"
] = "Unknown"

In [37]:
flights["Delay_Reason"].isnull().sum()

np.int64(0)

In [38]:
flights.isnull().sum()

Flight_ID                  0
Flight_Date                0
Airline_ID                 0
Aircraft_ID                0
Origin_Airport_ID          0
Destination_Airport_ID     0
Scheduled_Departure        0
Actual_Departure           0
Delay_Minutes              0
Delay_Reason               0
Status                     0
Flight_Duration_Min        0
Distance_KM                0
Seat_Capacity              0
Passengers                 0
Base_Fare_USD             35
Revenue_USD                0
Load_Factor_%              0
Season                     0
dtype: int64

In [39]:
flights["Base_Fare_USD"].describe()

count    4965.000000
mean      361.127492
std       168.125301
min        70.000000
25%       218.000000
50%       362.000000
75%       506.000000
max       649.000000
Name: Base_Fare_USD, dtype: float64

In [40]:
flights["Base_Fare_USD"] = flights["Base_Fare_USD"].fillna(flights["Base_Fare_USD"].median())
flights["Base_Fare_USD"]

0       361.0
1       624.0
2       541.0
3       469.0
4       214.0
        ...
4995    533.0
4996    279.0
4997    396.0
4998    496.0
4999    185.0
Name: Base_Fare_USD, Length: 5000, dtype: float64

In [41]:
flights["Base_Fare_USD"].isnull().sum()

np.int64(0)

In [42]:
passengers

,Passenger_ID,Passenger_Name,Age,Gender,Nationality,Travel_Class,Flight_ID,Booking_Channel,Ticket_Price_USD,Satisfaction_Score,Satisfaction_Level
0,PS00001,Noah Smith,52,Female,Canadian,Economy,FL03578,Mobile App,890.0,3.8,Satisfied
1,PS00002,Isha Reddy,46,Female,British,Premium Economy,FL04512,Travel Agent,725.0,4.4,Very Satisfied
2,PS00003,Rohan Gupta,38,Female,Canadian,Premium Economy,FL03411,Website,259.0,4.2,Very Satisfied
3,PS00004,Noah Reddy,20,Male,American,Business,FL01574,Website,1439.0,4.9,Very Satisfied
4,PS00005,Kabir Singh,49,Male,Canadian,Economy,FL00761,Website,659.0,4.5,Very Satisfied
...,...,...,...,...,...,...,...,...,...,...,...
15055,PS06108,Aditya Patel,28,Male,German,Economy,FL04321,Website,708.0,3.8,Satisfied
15056,PS03982,Ananya Kumar,65,Female,Canadian,Business,FL04193,Airport Counter,95.0,2.8,Dissatisfied
15057,PS08032,Isha Singh,25,Male,German,Business,FL02507,Travel Agent,1158.0,4.6,Very Satisfied
15058,PS02183,Noah Patel,33,Female,American,Business,FL03138,Mobile App,183.0,3.6,Satisfied
15059,PS13269,Vikram Brown,20,Female,Indian,Economy,FL03994,Website,1198.0,4.3,Very Satisfied

In [43]:
# Add origin city
routes = routes.merge(
    airports[["Airport_ID", "City"]],
    left_on="Origin_Airport_ID",
    right_on="Airport_ID",
    how="left"
).rename(columns={"City": "Origin_City"}).drop(columns=["Airport_ID"])

# Add destination city
routes = routes.merge(
    airports[["Airport_ID", "City"]],
    left_on="Destination_Airport_ID",
    right_on="Airport_ID",
    how="left"
).rename(columns={"City": "Destination_City"}).drop(columns=["Airport_ID"])

# Create route name
routes["Route_Name"] = (
    routes["Origin_City"] + " → " + routes["Destination_City"]
)

In [140]:
routes.columns

Index(['Origin_Airport_ID', 'Destination_Airport_ID', 'Flights',
       'Total_Passengers', 'Total_Revenue_USD', 'Avg_Load_Factor_Pct',
       'Avg_Delay_Minutes', 'Route_ID', 'Origin_City', 'Destination_City',
       'Route_Name'],
      dtype='str')

In [44]:
passengers.isnull().sum()

Passenger_ID           0
Passenger_Name         0
Age                    0
Gender                 0
Nationality            0
Travel_Class          60
Flight_ID              0
Booking_Channel        0
Ticket_Price_USD      60
Satisfaction_Score    60
Satisfaction_Level    40
dtype: int64

In [45]:
passengers.duplicated().sum()

np.int64(60)

In [46]:
passengers[passengers.duplicated(keep=False)].sort_values(by=list(passengers.columns))

,Passenger_ID,Passenger_Name,Age,Gender,Nationality,Travel_Class,Flight_ID,Booking_Channel,Ticket_Price_USD,Satisfaction_Score,Satisfaction_Level
552,PS00553,Nisha Iyer,18,Male,Canadian,Economy,FL02990,Airport Counter,547.0,3.2,Satisfied
15048,PS00553,Nisha Iyer,18,Male,Canadian,Economy,FL02990,Airport Counter,547.0,3.2,Satisfied
736,PS00737,Ananya Smith,44,Male,Indian,Economy,FL02483,Mobile App,648.0,3.7,Satisfied
15044,PS00737,Ananya Smith,44,Male,Indian,Economy,FL02483,Mobile App,648.0,3.7,Satisfied
924,PS00925,Ananya Joseph,68,Male,Australian,Premium Economy,FL00390,Website,1011.0,4.6,Very Satisfied
...,...,...,...,...,...,...,...,...,...,...,...
15007,PS14353,Aarav Taylor,25,Male,Australian,Economy,FL00668,Website,208.0,4.2,Very Satisfied
14396,PS14397,Aarav Nair,36,Female,German,Economy,FL02853,Website,961.0,4.7,Very Satisfied
15041,PS14397,Aarav Nair,36,Female,German,Economy,FL02853,Website,961.0,4.7,Very Satisfied
14889,PS14890,Nisha Sharma,73,Male,American,Business,FL00512,Mobile App,903.0,3.7,Satisfied
15017,PS14890,Nisha Sharma,73,Male,American,Business,FL00512,Mobile App,903.0,3.7,Satisfied

In [47]:
passengers=passengers.drop_duplicates()
passengers

,Passenger_ID,Passenger_Name,Age,Gender,Nationality,Travel_Class,Flight_ID,Booking_Channel,Ticket_Price_USD,Satisfaction_Score,Satisfaction_Level
0,PS00001,Noah Smith,52,Female,Canadian,Economy,FL03578,Mobile App,890.0,3.8,Satisfied
1,PS00002,Isha Reddy,46,Female,British,Premium Economy,FL04512,Travel Agent,725.0,4.4,Very Satisfied
2,PS00003,Rohan Gupta,38,Female,Canadian,Premium Economy,FL03411,Website,259.0,4.2,Very Satisfied
3,PS00004,Noah Reddy,20,Male,American,Business,FL01574,Website,1439.0,4.9,Very Satisfied
4,PS00005,Kabir Singh,49,Male,Canadian,Economy,FL00761,Website,659.0,4.5,Very Satisfied
...,...,...,...,...,...,...,...,...,...,...,...
14995,PS14996,Aarav Smith,24,Other,American,Business,FL04814,Website,1186.0,2.8,Dissatisfied
14996,PS14997,Priya Sharma,57,Male,Indian,Economy,FL00461,Website,1192.0,2.1,Dissatisfied
14997,PS14998,Ananya Smith,60,Male,Australian,Economy,FL02280,Website,741.0,3.8,Satisfied
14998,PS14999,Ananya Kumar,38,Male,Australian,Premium Economy,FL04480,Travel Agent,1292.0,3.0,Dissatisfied
14999,PS15000,Nisha Smith,63,Male,Canadian,Economy,FL03870,Website,1352.0,5.0,Very Satisfied

In [48]:
passengers.duplicated().sum()

np.int64(0)

In [49]:
passengers.isnull().sum()

Passenger_ID           0
Passenger_Name         0
Age                    0
Gender                 0
Nationality            0
Travel_Class          60
Flight_ID              0
Booking_Channel        0
Ticket_Price_USD      60
Satisfaction_Score    60
Satisfaction_Level    40
dtype: int64

In [50]:
passengers[passengers["Travel_Class"].isnull()]

,Passenger_ID,Passenger_Name,Age,Gender,Nationality,Travel_Class,Flight_ID,Booking_Channel,Ticket_Price_USD,Satisfaction_Score,Satisfaction_Level
39,PS00040,Priya Brown,72,Male,UAE,NaN,FL00227,Travel Agent,1347.0,4.5,Very Satisfied
456,PS00457,Olivia Reddy,74,Female,British,NaN,FL01248,Website,1300.0,4.4,Very Satisfied
564,PS00565,Aisha Sharma,29,Male,Indian,NaN,FL02211,Airport Counter,707.0,4.4,Very Satisfied
646,PS00647,Rohan Joseph,47,Male,Canadian,NaN,FL01247,Airport Counter,482.0,4.7,Very Satisfied
662,PS00663,Karan Joseph,68,Male,Australian,NaN,FL01920,Mobile App,539.0,4.0,Satisfied
717,PS00718,Noah Wilson,39,Female,UAE,NaN,FL04630,Mobile App,1182.0,3.2,Satisfied
883,PS00884,Aditya Thomas,47,Female,German,NaN,FL03648,Mobile App,1191.0,4.1,Very Satisfied
1510,PS01511,Aarav Wilson,72,Male,UAE,NaN,FL01399,Mobile App,283.0,4.4,Very Satisfied
1520,PS01521,Noah Thomas,45,Female,Australian,NaN,FL03586,Mobile App,597.0,4.0,Satisfied
1699,PS01700,Isha Brown,49,Male,Australian,NaN,FL00686,Travel Agent,550.0,5.0,Very Satisfied
1911,PS01912,Daniel Wilson,32,Male,UAE,NaN,FL00013,Website,1444.0,2.4,Dissatisfied
1923,PS01924,Rohan Martin,24,Male,German,NaN,FL02475,Website,1258.0,3.1,Satisfied
2046,PS02047,Emma Brown,32,Male,Singaporean,NaN,FL01814,Website,217.0,5.0,Very Satisfied
2188,PS02189,Vikram Martin,66,Male,Canadian,NaN,FL03876,Mobile App,1063.0,4.2,Very Satisfied
2339,PS02340,Olivia Smith,70,Female,German,NaN,FL02506,Website,1492.0,3.6,Satisfied
2751,PS02752,Olivia Nair,72,Male,German,NaN,FL04207,Mobile App,127.0,4.6,Very Satisfied
3238,PS03239,Aisha Singh,24,Female,Singaporean,NaN,FL04334,Airport Counter,291.0,3.2,Satisfied
3574,PS03575,Priya Patel,24,Male,Australian,NaN,FL00468,Airport Counter,778.0,4.5,Very Satisfied
3606,PS03607,Noah Thomas,37,Female,British,NaN,FL00734,Website,742.0,5.0,Very Satisfied
3624,PS03625,Aarav Iyer,18,Male,Canadian,NaN,FL04586,Mobile App,498.0,4.3,Very Satisfied
3627,PS03628,Sneha Sharma,65,Male,Indian,NaN,FL00865,Mobile App,310.0,4.2,Very Satisfied
3881,PS03882,Nisha Singh,31,Male,German,NaN,FL01347,Website,867.0,4.0,Satisfied
3992,PS03993,Diya Patel,22,Female,Australian,NaN,FL04995,Mobile App,658.0,3.9,Satisfied
3998,PS03999,Meera Kumar,29,Female,UAE,NaN,FL00490,Travel Agent,1347.0,3.9,Satisfied
4152,PS04153,Noah Iyer,75,Male,Australian,NaN,FL03698,Website,451.0,3.9,Satisfied
4180,PS04181,Olivia Brown,63,Other,American,NaN,FL03581,Website,451.0,4.1,Very Satisfied
4771,PS04772,Emma Taylor,50,Female,British,NaN,FL01862,Mobile App,1232.0,4.5,Very Satisfied
5136,PS05137,Meera Reddy,43,Female,UAE,NaN,FL01168,Airport Counter,131.0,4.6,Very Satisfied
5278,PS05279,Aisha Taylor,51,Female,Australian,NaN,FL04097,Website,1465.0,4.4,Very Satisfied
5381,PS05382,Meera Iyer,35,Female,American,NaN,FL04411,Website,379.0,3.4,Satisfied
5477,PS05478,Priya Gupta,26,Female,British,NaN,FL00086,Website,1279.0,4.6,Very Satisfied
5500,PS05501,Priya Patel,44,Female,Indian,NaN,FL00925,Website,473.0,4.1,Very Satisfied
5566,PS05567,Ananya Brown,40,Female,Australian,NaN,FL04054,Mobile App,873.0,4.7,Very Satisfied
6119,PS06120,Noah Sharma,70,Male,German,NaN,FL03814,Mobile App,128.0,4.2,Very Satisfied
6335,PS06336,Karan Martin,50,Male,Australian,NaN,FL02227,Website,663.0,3.8,Satisfied
6566,PS06567,Olivia Smith,39,Male,American,NaN,FL02568,Travel Agent,447.0,3.6,Satisfied
7212,PS07213,Rahul Martin,39,Female,Australian,NaN,FL00634,Airport Counter,614.0,3.5,Satisfied
7848,PS07849,Aarav Joseph,45,Male,Singaporean,NaN,FL01743,Travel Agent,648.0,4.4,Very Satisfied
8192,PS08193,Olivia Martin,31,Female,British,NaN,FL01099,Website,523.0,3.7,Satisfied
8306,PS08307,Sneha Nair,22,Female,Australian,NaN,FL04600,Mobile App,346.0,4.9,Very Satisfied
8629,PS08630,Rahul Joseph,39,Male,UAE,NaN,FL00915,Airport Counter,453.0,2.1,Dissatisfied
8770,PS08771,Rahul Nair,54,Male,German,NaN,FL01879,Mobile App,668.0,4.5,Very Satisfied
9033,PS09034,Isha Brown,66,Male,American,NaN,FL03773,Website,1359.0,4.8,Very Satisfied
9038,PS09039,Vikram Iyer,30,Male,Indian,NaN,FL01449,Mobile App,451.0,2.9,Dissatisfied
9266,PS09267,Arjun Iyer,63,Female,Australian,NaN,FL00229,Mobile App,425.0,5.0,Very Satisfied
9836,PS09837,Rohan Wilson,49,Male,Australian,NaN,FL02453,Travel Agent,1211.0,4.7,Very Satisfied
9985,PS09986,Rohan Sharma,28,Female,Indian,NaN,FL04433,Airport Counter,629.0,3.6,Satisfied
10002,PS10003,Priya Reddy,24,Female,German,NaN,FL04119,Airport Counter,502.0,3.3,Satisfied
10123,PS10124,Aditya Smith,26,Female,American,NaN,FL03783,Travel Agent,123.0,3.6,Satisfied
10293,PS10294,Isha Gupta,56,Male,Canadian,NaN,FL02309,Travel Agent,1138.0,4.4,Very Satisfied
10392,PS10393,Nisha Patel,56,Male,Indian,NaN,FL00363,Website,1267.0,3.5,Satisfied
11361,PS11362,Karan Martin,46,Male,Australian,NaN,FL00779,Website,1254.0,4.6,Very Satisfied
11415,PS11416,Sneha Patel,51,Female,Indian,NaN,FL02121,Website,487.0,2.1,Dissatisfied
11714,PS11715,Priya Singh,19,Male,Australian,NaN,FL00350,Travel Agent,496.0,3.8,Satisfied
11829,PS11830,Rahul Reddy,69,Male,Australian,NaN,FL01167,Website,1011.0,5.0,Very Satisfied
12974,PS12975,Rahul Sharma,59,Male,American,NaN,FL03008,Website,671.0,3.5,Satisfied
13680,PS13681,Olivia Joseph,28,Female,Indian,NaN,FL04742,Website,722.0,3.7,Satisfied
13685,PS13686,Emma Gupta,74,Female,German,NaN,FL02124,Mobile App,1286.0,4.1,Very Satisfied
14407,PS14408,Karan Wilson,32,Male,UAE,NaN,FL03723,Mobile App,662.0,4.2,Very Satisfied
14478,PS14479,Rahul Nair,27,Male,Indian,NaN,FL00899,Website,247.0,3.7,Satisfied

In [51]:
passengers["Travel_Class"].value_counts(dropna=False)

Travel_Class
Economy            9250
Premium Economy    2690
Business           2541
First               459
NaN                  60
Name: count, dtype: int64

In [52]:
print(passengers.columns.tolist())

['Passenger_ID', 'Passenger_Name', 'Age', 'Gender', 'Nationality', 'Travel_Class', 'Flight_ID', 'Booking_Channel', 'Ticket_Price_USD', 'Satisfaction_Score', 'Satisfaction_Level']

In [53]:
passengers["Travel_Class"] = passengers["Travel_Class"].fillna(passengers["Travel_Class"].mode()[0])
passengers["Travel_Class"]

0                Economy
1        Premium Economy
2        Premium Economy
3               Business
4                Economy
              ...
14995           Business
14996            Economy
14997            Economy
14998    Premium Economy
14999            Economy
Name: Travel_Class, Length: 15000, dtype: str

In [54]:
passengers["Travel_Class"].isnull().sum()

np.int64(0)

In [55]:
passengers["Ticket_Price_USD"].describe()

count    14940.000000
mean       782.497523
std        411.673824
min         70.000000
25%        421.000000
50%        784.000000
75%       1141.000000
max       1499.000000
Name: Ticket_Price_USD, dtype: float64

In [56]:
passengers["Ticket_Price_USD"] = passengers["Ticket_Price_USD"].fillna(passengers["Ticket_Price_USD"].median())

In [57]:
passengers["Ticket_Price_USD"].isnull().sum()

np.int64(0)

In [58]:
passengers["Satisfaction_Score"].describe()

count    14940.000000
mean         3.967959
std          0.734591
min          1.000000
25%          3.600000
50%          4.100000
75%          4.500000
max          5.000000
Name: Satisfaction_Score, dtype: float64

In [59]:
passengers["Satisfaction_Score"] = passengers["Satisfaction_Score"].fillna(passengers["Satisfaction_Score"].median())

In [60]:
passengers["Satisfaction_Score"].isnull().sum()

np.int64(0)

In [61]:
passengers.groupby("Satisfaction_Score")["Satisfaction_Level"].value_counts()

Satisfaction_Score  Satisfaction_Level
1.0                 Very Dissatisfied        7
1.1                 Very Dissatisfied       11
1.2                 Very Dissatisfied        8
1.3                 Very Dissatisfied        9
1.4                 Very Dissatisfied       10
1.5                 Very Dissatisfied       17
1.6                 Very Dissatisfied       37
1.7                 Very Dissatisfied       26
1.8                 Very Dissatisfied       56
1.9                 Very Dissatisfied       55
2.0                 Very Dissatisfied       69
2.1                 Dissatisfied            86
2.2                 Dissatisfied            89
2.3                 Dissatisfied            85
2.4                 Dissatisfied           109
2.5                 Dissatisfied           140
2.6                 Dissatisfied           124
2.7                 Dissatisfied           142
2.8                 Dissatisfied           162
2.9                 Dissatisfied           201
3.0                 Dissatisfied           209
3.1                 Satisfied              259
3.2                 Satisfied              312
3.3                 Satisfied              368
3.4                 Satisfied              408
3.5                 Satisfied              475
3.6                 Satisfied              654
3.7                 Satisfied              701
3.8                 Satisfied              736
3.9                 Satisfied              816
4.0                 Satisfied              884
4.1                 Very Satisfied         960
                    Satisfied               23
                    Dissatisfied             6
                    Very Dissatisfied        1
4.2                 Very Satisfied         919
4.3                 Very Satisfied         877
4.4                 Very Satisfied         837
4.5                 Very Satisfied         724
4.6                 Very Satisfied         681
4.7                 Very Satisfied         586
4.8                 Very Satisfied         517
4.9                 Very Satisfied         434
5.0                 Very Satisfied        1130
Name: count, dtype: int64

In [62]:
passengers[passengers["Satisfaction_Level"].isnull()][["Satisfaction_Score", "Satisfaction_Level"]]

       Satisfaction_Score Satisfaction_Level
1277                  3.3                NaN
1459                  2.9                NaN
1588                  4.0                NaN
1905                  3.7                NaN
2532                  2.7                NaN
4456                  4.1                NaN
4646                  4.6                NaN
4707                  2.8                NaN
4721                  4.7                NaN
5499                  3.9                NaN
5538                  3.5                NaN
5738                  2.7                NaN
5914                  2.6                NaN
5977                  4.6                NaN
5978                  4.1                NaN
6024                  3.7                NaN
6080                  3.4                NaN
7102                  2.5                NaN
7529                  3.6                NaN
7757                  3.4                NaN
7867                  3.8                NaN
8206                  4.2                NaN
8291                  4.3                NaN
10232                 4.4                NaN
10322                 4.0                NaN
10581                 3.6                NaN
10670                 2.4                NaN
10845                 4.1                NaN
11075                 3.4                NaN
11199                 3.1                NaN
11793                 2.2                NaN
12023                 3.8                NaN
12239                 4.5                NaN
12376                 4.6                NaN
12413                 4.3                NaN
12596                 3.3                NaN
12697                 2.3                NaN
13218                 2.9                NaN
13380                 4.1                NaN
14357                 3.4                NaN

In [63]:
passengers.loc[
    passengers["Satisfaction_Level"].isnull() &
    (passengers["Satisfaction_Score"] <= 2.0),
    "Satisfaction_Level"
] = "Very Dissatisfied"

passengers.loc[
    passengers["Satisfaction_Level"].isnull() &
    (passengers["Satisfaction_Score"] <= 3.0),
    "Satisfaction_Level"
] = "Dissatisfied"

passengers.loc[
    passengers["Satisfaction_Level"].isnull() &
    (passengers["Satisfaction_Score"] <= 4.0),
    "Satisfaction_Level"
] = "Satisfied"

passengers.loc[
    passengers["Satisfaction_Level"].isnull() &
    (passengers["Satisfaction_Score"] >= 4.1),
    "Satisfaction_Level"
] = "Very Satisfied"

In [64]:
passengers["Satisfaction_Level"].isnull().sum()

np.int64(0)

In [65]:
passengers.isnull().sum()

Passenger_ID          0
Passenger_Name        0
Age                   0
Gender                0
Nationality           0
Travel_Class          0
Flight_ID             0
Booking_Channel       0
Ticket_Price_USD      0
Satisfaction_Score    0
Satisfaction_Level    0
dtype: int64

In [66]:
routes

,Origin_Airport_ID,Destination_Airport_ID,Flights,Total_Passengers,Total_Revenue_USD,Avg_Load_Factor_Pct,Avg_Delay_Minutes,Route_ID,Origin_City,Destination_City,Route_Name
0,AP001,AP002,8,1810,700570.0,76.131595,28.500000,RT00001,Chennai,Delhi,Chennai → Delhi
1,AP001,AP003,11,2430,1072337.0,71.595602,8.000000,RT00002,Chennai,Mumbai,Chennai → Mumbai
2,AP001,AP004,2,363,125721.0,69.893939,3.000000,RT00003,Chennai,Bengaluru,Chennai → Bengaluru
3,AP001,AP005,5,1017,412519.0,73.240436,7.600000,RT00004,Chennai,Hyderabad,Chennai → Hyderabad
4,AP001,AP006,6,1226,450219.0,71.903426,61.000000,RT00005,Chennai,Kolkata,Chennai → Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
867,AP015,AP030,5,1276,355702.0,71.377532,6.200000,RT00434,Los Angeles,Hahn,Los Angeles → Hahn
868,AP030,AP002,5,986,395188.0,69.587541,37.800000,RT00840,Hahn,Delhi,Hahn → Delhi
869,AP009,AP022,2,352,NaN,73.544974,11.000000,RT00252,Ahmedabad,Hong Kong,Ahmedabad → Hong Kong
870,AP025,AP003,6,918,369434.0,60.328197,30.333333,RT00697,Amsterdam,Mumbai,Amsterdam → Mumbai
871,AP006,AP002,5,1086,471941.0,80.802368,7.200000,RT00147,Kolkata,Delhi,Kolkata → Delhi

In [67]:
routes.isnull().sum()

Origin_Airport_ID           0
Destination_Airport_ID      0
Flights                     0
Total_Passengers            0
Total_Revenue_USD          11
Avg_Load_Factor_Pct        10
Avg_Delay_Minutes          10
Route_ID                    0
Origin_City                58
Destination_City           57
Route_Name                113
dtype: int64

In [68]:
routes.duplicated().sum()

np.int64(5)

In [69]:
routes[routes.duplicated(keep=False)].sort_values(by=list(routes.columns))

,Origin_Airport_ID,Destination_Airport_ID,Flights,Total_Passengers,Total_Revenue_USD,Avg_Load_Factor_Pct,Avg_Delay_Minutes,Route_ID,Origin_City,Destination_City,Route_Name
146,AP006,AP002,5,1086,471941.0,80.802368,7.200000,RT00147,Kolkata,Delhi,Kolkata → Delhi
871,AP006,AP002,5,1086,471941.0,80.802368,7.200000,RT00147,Kolkata,Delhi,Kolkata → Delhi
251,AP009,AP022,2,352,NaN,73.544974,11.000000,RT00252,Ahmedabad,Hong Kong,Ahmedabad → Hong Kong
869,AP009,AP022,2,352,NaN,73.544974,11.000000,RT00252,Ahmedabad,Hong Kong,Ahmedabad → Hong Kong
433,AP015,AP030,5,1276,355702.0,71.377532,6.200000,RT00434,Los Angeles,Hahn,Los Angeles → Hahn
867,AP015,AP030,5,1276,355702.0,71.377532,6.200000,RT00434,Los Angeles,Hahn,Los Angeles → Hahn
696,AP025,AP003,6,918,369434.0,60.328197,30.333333,RT00697,Amsterdam,Mumbai,Amsterdam → Mumbai
870,AP025,AP003,6,918,369434.0,60.328197,30.333333,RT00697,Amsterdam,Mumbai,Amsterdam → Mumbai
839,AP030,AP002,5,986,395188.0,69.587541,37.800000,RT00840,Hahn,Delhi,Hahn → Delhi
868,AP030,AP002,5,986,395188.0,69.587541,37.800000,RT00840,Hahn,Delhi,Hahn → Delhi

In [70]:
routes=routes.drop_duplicates()

In [71]:
routes

,Origin_Airport_ID,Destination_Airport_ID,Flights,Total_Passengers,Total_Revenue_USD,Avg_Load_Factor_Pct,Avg_Delay_Minutes,Route_ID,Origin_City,Destination_City,Route_Name
0,AP001,AP002,8,1810,700570.0,76.131595,28.500000,RT00001,Chennai,Delhi,Chennai → Delhi
1,AP001,AP003,11,2430,1072337.0,71.595602,8.000000,RT00002,Chennai,Mumbai,Chennai → Mumbai
2,AP001,AP004,2,363,125721.0,69.893939,3.000000,RT00003,Chennai,Bengaluru,Chennai → Bengaluru
3,AP001,AP005,5,1017,412519.0,73.240436,7.600000,RT00004,Chennai,Hyderabad,Chennai → Hyderabad
4,AP001,AP006,6,1226,450219.0,71.903426,61.000000,RT00005,Chennai,Kolkata,Chennai → Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
862,AP030,AP025,8,1468,564234.0,71.966363,6.750000,RT00863,Hahn,Amsterdam,Hahn → Amsterdam
863,AP030,AP026,2,429,124093.0,84.487101,105.000000,RT00864,Hahn,Toronto,Hahn → Toronto
864,AP030,AP027,9,1998,714380.0,80.234969,26.888889,RT00865,Hahn,Istanbul,Hahn → Istanbul
865,AP030,AP028,11,2365,898095.0,77.806862,12.909091,RT00866,Hahn,Abu Dhabi,Hahn → Abu Dhabi
866,AP030,AP029,3,524,114107.0,72.531987,4.333333,RT00867,Hahn,Cape Town,Hahn → Cape Town

In [72]:
routes.isnull().sum()

Origin_Airport_ID           0
Destination_Airport_ID      0
Flights                     0
Total_Passengers            0
Total_Revenue_USD          10
Avg_Load_Factor_Pct        10
Avg_Delay_Minutes          10
Route_ID                    0
Origin_City                58
Destination_City           57
Route_Name                113
dtype: int64

In [73]:
routes["Total_Revenue_USD"].describe()

count    8.570000e+02
mean     4.348543e+05
std      2.089714e+05
min      1.147000e+04
25%      2.802460e+05
50%      4.167310e+05
75%      5.661380e+05
max      1.281396e+06
Name: Total_Revenue_USD, dtype: float64

In [74]:
routes["Total_Revenue_USD"]=routes["Total_Revenue_USD"].fillna(routes["Total_Revenue_USD"].median())

In [75]:
routes["Total_Revenue_USD"].isnull().sum()

np.int64(0)

In [76]:
routes["Avg_Load_Factor_Pct"].describe()

count    857.000000
mean      73.914318
std        7.858153
min       34.444444
25%       70.850168
50%       74.817553
75%       78.949950
max       99.000000
Name: Avg_Load_Factor_Pct, dtype: float64

In [77]:
routes["Avg_Load_Factor_Pct"] = routes["Avg_Load_Factor_Pct"].fillna(routes["Avg_Load_Factor_Pct"].median())

In [78]:
routes["Avg_Load_Factor_Pct"].isnull().sum()

np.int64(0)

In [79]:
routes["Avg_Delay_Minutes"].describe()

count    857.000000
mean      26.188682
std       20.123273
min        0.500000
25%        9.400000
50%       22.200000
75%       37.272727
max      173.000000
Name: Avg_Delay_Minutes, dtype: float64

In [80]:
routes["Avg_Delay_Minutes"]=routes["Avg_Delay_Minutes"].fillna(routes["Avg_Delay_Minutes"].median())

In [81]:
routes["Avg_Delay_Minutes"].isnull().sum()

np.int64(0)

In [141]:
routes.isnull().sum()

Origin_Airport_ID           0
Destination_Airport_ID      0
Flights                     0
Total_Passengers            0
Total_Revenue_USD           0
Avg_Load_Factor_Pct         0
Avg_Delay_Minutes           0
Route_ID                    0
Origin_City                58
Destination_City           57
Route_Name                113
dtype: int64

In [146]:
routes[
    routes["Origin_City"].isnull() |
    routes["Destination_City"].isnull()
][[
    "Route_ID",
    "Origin_Airport_ID",
    "Destination_Airport_ID",
    "Origin_City",
    "Destination_City"
]].head(20)

,Route_ID,Origin_Airport_ID,Destination_Airport_ID,Origin_City,Destination_City
8,RT00009,AP001,AP010,Chennai,NaN
11,RT00012,AP001,AP013,Chennai,NaN
37,RT00038,AP002,AP010,Delhi,NaN
40,RT00041,AP002,AP013,Delhi,NaN
66,RT00067,AP003,AP010,Mumbai,NaN
69,RT00070,AP003,AP013,Mumbai,NaN
95,RT00096,AP004,AP010,Bengaluru,NaN
98,RT00099,AP004,AP013,Bengaluru,NaN
124,RT00125,AP005,AP010,Hyderabad,NaN
127,RT00128,AP005,AP013,Hyderabad,NaN
153,RT00154,AP006,AP010,Kolkata,NaN
156,RT00157,AP006,AP013,Kolkata,NaN
182,RT00183,AP007,AP010,Kochi,NaN
185,RT00186,AP007,AP013,Kochi,NaN
211,RT00212,AP008,AP010,Pune,NaN
214,RT00215,AP008,AP013,Pune,NaN
239,RT00240,AP009,AP010,Ahmedabad,NaN
242,RT00243,AP009,AP013,Ahmedabad,NaN
260,RT00261,AP010,AP001,NaN,Chennai
261,RT00262,AP010,AP002,NaN,Delhi

In [147]:
print(
    routes.loc[
        ~routes["Origin_Airport_ID"].isin(airports["Airport_ID"]),
        "Origin_Airport_ID"
    ].unique()
)

print(
    routes.loc[
        ~routes["Destination_Airport_ID"].isin(airports["Airport_ID"]),
        "Destination_Airport_ID"
    ].unique()
)

<StringArray>
[]
Length: 0, dtype: str
<StringArray>
[]
Length: 0, dtype: str

In [148]:
airports[airports["Airport_ID"].isin(["AP010", "AP013"])]

,Airport_ID,Airport_Name,City,Country,IATA_Code,Latitude,Longitude
9,AP010,Goa International Airport,Goa,India,GOX,15.38,73.8310
12,AP013,Heathrow Airport,London,UK,LHR,51.47,-0.4543

In [149]:
airport_city = dict(zip(airports["Airport_ID"], airports["City"]))

routes["Origin_City"] = routes["Origin_Airport_ID"].map(airport_city)
routes["Destination_City"] = routes["Destination_Airport_ID"].map(airport_city)

routes["Route_Name"] = (
    routes["Origin_City"] + " → " + routes["Destination_City"]
)

In [150]:
routes[
    ["Route_ID", "Origin_Airport_ID", "Destination_Airport_ID",
     "Origin_City", "Destination_City", "Route_Name"]
].head(20)

,Route_ID,Origin_Airport_ID,Destination_Airport_ID,Origin_City,Destination_City,Route_Name
0,RT00001,AP001,AP002,Chennai,Delhi,Chennai → Delhi
1,RT00002,AP001,AP003,Chennai,Mumbai,Chennai → Mumbai
2,RT00003,AP001,AP004,Chennai,Bengaluru,Chennai → Bengaluru
3,RT00004,AP001,AP005,Chennai,Hyderabad,Chennai → Hyderabad
4,RT00005,AP001,AP006,Chennai,Kolkata,Chennai → Kolkata
5,RT00006,AP001,AP007,Chennai,Kochi,Chennai → Kochi
6,RT00007,AP001,AP008,Chennai,Pune,Chennai → Pune
7,RT00008,AP001,AP009,Chennai,Ahmedabad,Chennai → Ahmedabad
8,RT00009,AP001,AP010,Chennai,Goa,Chennai → Goa
9,RT00010,AP001,AP011,Chennai,Dubai,Chennai → Dubai
10,RT00011,AP001,AP012,Chennai,Singapore,Chennai → Singapore
11,RT00012,AP001,AP013,Chennai,London,Chennai → London
12,RT00013,AP001,AP014,Chennai,New York,Chennai → New York
13,RT00014,AP001,AP015,Chennai,Los Angeles,Chennai → Los Angeles
14,RT00015,AP001,AP016,Chennai,Doha,Chennai → Doha
15,RT00016,AP001,AP017,Chennai,Frankfurt,Chennai → Frankfurt
16,RT00017,AP001,AP018,Chennai,Sydney,Chennai → Sydney
17,RT00018,AP001,AP019,Chennai,Melbourne,Chennai → Melbourne
18,RT00019,AP001,AP020,Chennai,Bangkok,Chennai → Bangkok
19,RT00020,AP001,AP021,Chennai,Kuala Lumpur,Chennai → Kuala Lumpur

In [151]:
print(routes["Origin_City"].isnull().sum())
print(routes["Destination_City"].isnull().sum())
print(routes["Route_Name"].isnull().sum())

0
0
0

In [157]:
routes.isnull().sum()

Origin_Airport_ID         0
Destination_Airport_ID    0
Flights                   0
Total_Passengers          0
Total_Revenue_USD         0
Avg_Load_Factor_Pct       0
Avg_Delay_Minutes         0
Route_ID                  0
Origin_City               0
Destination_City          0
Route_Name                0
dtype: int64

In [158]:
routes

,Origin_Airport_ID,Destination_Airport_ID,Flights,Total_Passengers,Total_Revenue_USD,Avg_Load_Factor_Pct,Avg_Delay_Minutes,Route_ID,Origin_City,Destination_City,Route_Name
0,AP001,AP002,8,1810,700570.0,76.131595,28.500000,RT00001,Chennai,Delhi,Chennai → Delhi
1,AP001,AP003,11,2430,1072337.0,71.595602,8.000000,RT00002,Chennai,Mumbai,Chennai → Mumbai
2,AP001,AP004,2,363,125721.0,69.893939,3.000000,RT00003,Chennai,Bengaluru,Chennai → Bengaluru
3,AP001,AP005,5,1017,412519.0,73.240436,7.600000,RT00004,Chennai,Hyderabad,Chennai → Hyderabad
4,AP001,AP006,6,1226,450219.0,71.903426,61.000000,RT00005,Chennai,Kolkata,Chennai → Kolkata
...,...,...,...,...,...,...,...,...,...,...,...
862,AP030,AP025,8,1468,564234.0,71.966363,6.750000,RT00863,Hahn,Amsterdam,Hahn → Amsterdam
863,AP030,AP026,2,429,124093.0,84.487101,105.000000,RT00864,Hahn,Toronto,Hahn → Toronto
864,AP030,AP027,9,1998,714380.0,80.234969,26.888889,RT00865,Hahn,Istanbul,Hahn → Istanbul
865,AP030,AP028,11,2365,898095.0,77.806862,12.909091,RT00866,Hahn,Abu Dhabi,Hahn → Abu Dhabi
866,AP030,AP029,3,524,114107.0,72.531987,4.333333,RT00867,Hahn,Cape Town,Hahn → Cape Town

In [83]:
airlines

  Airline_ID  Airline_Name    Country
0      AL001        SkyJet      India
1      AL002     AeroVista        UAE
2      AL003  Global Wings         UK
3      AL004  Blue Horizon  Singapore
4      AL005    AirConnect        NaN
5      AL006       FlyHigh        USA
6      AL007       StarAir      Qatar
7      AL008     CloudNine    Germany
8      AL009   Pacific Air  Australia
9      AL010      MetroAir      India

In [84]:
airlines[airlines["Country"].isnull()]

  Airline_ID Airline_Name Country
4      AL005   AirConnect     NaN

In [85]:
airports

,Airport_ID,Airport_Name,City,Country,IATA_Code,Latitude,Longitude
0,AP001,Chennai International Airport,Chennai,India,MAA,12.9941,80.1709
1,AP002,Indira Gandhi International Airport,Delhi,India,DEL,28.5562,77.1000
2,AP003,Chhatrapati Shivaji Maharaj International Airport,Mumbai,India,BOM,19.0896,72.8656
3,AP004,Kempegowda International Airport,Bengaluru,India,BLR,13.1986,77.7066
4,AP005,Rajiv Gandhi International Airport,Hyderabad,India,HYD,17.2403,78.4294
5,AP006,Netaji Subhas Chandra Bose International Airport,Kolkata,India,CCU,22.6547,88.4467
6,AP007,Cochin International Airport,Kochi,India,COK,10.1520,76.4019
7,AP008,Pune Airport,Pune,NaN,PNQ,18.5821,73.9197
8,AP009,Sardar Vallabhbhai Patel International Airport,Ahmedabad,India,AMD,23.0732,72.6347
9,AP010,Goa International Airport,NaN,India,GOX,15.3800,73.8310
10,AP011,Dubai International Airport,Dubai,UAE,DXB,25.2532,55.3657
11,AP012,Singapore Changi Airport,Singapore,Singapore,SIN,1.3644,103.9915
12,AP013,Heathrow Airport,NaN,UK,LHR,51.4700,-0.4543
13,AP014,JFK International Airport,New York,USA,JFK,40.6413,-73.7781
14,AP015,Los Angeles International Airport,Los Angeles,USA,LAX,33.9416,-118.4085
15,AP016,Hamad International Airport,Doha,Qatar,DOH,NaN,51.6081
16,AP017,Frankfurt Airport,Frankfurt,Germany,FRA,50.0379,8.5622
17,AP018,Sydney Kingsford Smith Airport,Sydney,Australia,SYD,NaN,151.1753
18,AP019,Melbourne Airport,Melbourne,Australia,MEL,-37.6690,144.8410
19,AP020,Suvarnabhumi Airport,Bangkok,Thailand,BKK,13.6900,100.7501
20,AP021,Kuala Lumpur International Airport,Kuala Lumpur,Malaysia,KUL,2.7456,101.7072
21,AP022,Hong Kong International Airport,Hong Kong,China,HKG,22.3080,113.9185
22,AP023,Haneda Airport,Tokyo,Japan,HND,35.5494,139.7798
23,AP024,Charles de Gaulle Airport,Paris,France,CDG,49.0097,2.5479
24,AP025,Amsterdam Schiphol Airport,Amsterdam,Netherlands,AMS,52.3105,4.7683
25,AP026,Toronto Pearson International Airport,Toronto,Canada,YYZ,43.6777,-79.6248
26,AP027,Istanbul Airport,Istanbul,Turkey,IST,41.2753,28.7519
27,AP028,Abu Dhabi International Airport,Abu Dhabi,UAE,AUH,24.4330,54.6511
28,AP029,Cape Town International Airport,Cape Town,South Africa,CPT,-33.9715,18.6021
29,AP030,Frankfurt Hahn Airport,Hahn,NaN,HHN,49.9487,7.2639

In [86]:
airports.isnull().sum()

Airport_ID      0
Airport_Name    0
City            2
Country         2
IATA_Code       0
Latitude        2
Longitude       0
dtype: int64

In [87]:
airports[airports["City"].isnull()]

,Airport_ID,Airport_Name,City,Country,IATA_Code,Latitude,Longitude
9,AP010,Goa International Airport,NaN,India,GOX,15.38,73.8310
12,AP013,Heathrow Airport,NaN,UK,LHR,51.47,-0.4543

In [88]:
airports["City"] = airports["City"].fillna(airports["Airport_ID"].map({"AP010": "Goa","AP013": "London"}))
airports["City"]

0          Chennai
1            Delhi
2           Mumbai
3        Bengaluru
4        Hyderabad
5          Kolkata
6            Kochi
7             Pune
8        Ahmedabad
9              Goa
10           Dubai
11       Singapore
12          London
13        New York
14     Los Angeles
15            Doha
16       Frankfurt
17          Sydney
18       Melbourne
19         Bangkok
20    Kuala Lumpur
21       Hong Kong
22           Tokyo
23           Paris
24       Amsterdam
25         Toronto
26        Istanbul
27       Abu Dhabi
28       Cape Town
29            Hahn
Name: City, dtype: str

In [89]:
airports["City"].isnull().sum()

np.int64(0)

In [90]:
airports[airports["Country"].isnull()]

,Airport_ID,Airport_Name,City,Country,IATA_Code,Latitude,Longitude
7,AP008,Pune Airport,Pune,NaN,PNQ,18.5821,73.9197
29,AP030,Frankfurt Hahn Airport,Hahn,NaN,HHN,49.9487,7.2639

In [91]:
airports["Country"] = airports["Country"].fillna(airports["Airport_ID"].map({"AP008": "India","AP030": "Germany"}))
airports["Country"]

0            India
1            India
2            India
3            India
4            India
5            India
6            India
7            India
8            India
9            India
10             UAE
11       Singapore
12              UK
13             USA
14             USA
15           Qatar
16         Germany
17       Australia
18       Australia
19        Thailand
20        Malaysia
21           China
22           Japan
23          France
24     Netherlands
25          Canada
26          Turkey
27             UAE
28    South Africa
29         Germany
Name: Country, dtype: str

In [92]:
airports[airports["Latitude"].isnull()]

,Airport_ID,Airport_Name,City,Country,IATA_Code,Latitude,Longitude
15,AP016,Hamad International Airport,Doha,Qatar,DOH,NaN,51.6081
17,AP018,Sydney Kingsford Smith Airport,Sydney,Australia,SYD,NaN,151.1753

In [93]:
airports["Latitude"] = airports["Latitude"].fillna(airports["Airport_ID"].map({"AP016": 25.2731,"AP018": -33.9461}))
airports["Latitude"]

0     12.9941
1     28.5562
2     19.0896
3     13.1986
4     17.2403
5     22.6547
6     10.1520
7     18.5821
8     23.0732
9     15.3800
10    25.2532
11     1.3644
12    51.4700
13    40.6413
14    33.9416
15    25.2731
16    50.0379
17   -33.9461
18   -37.6690
19    13.6900
20     2.7456
21    22.3080
22    35.5494
23    49.0097
24    52.3105
25    43.6777
26    41.2753
27    24.4330
28   -33.9715
29    49.9487
Name: Latitude, dtype: float64

In [94]:
airports.isnull().sum()

Airport_ID      0
Airport_Name    0
City            0
Country         0
IATA_Code       0
Latitude        0
Longitude       0
dtype: int64

In [95]:
staffs

,Staff_ID,Staff_Name,Role,Department,Experience_Years,Salary_USD,Base_Airport_ID,Employment_Status
0,ST0001,Ananya Thomas,Cabin Crew,Ground Operations,1,112294,AP008,Active
1,ST0002,Sneha Brown,Cabin Crew,Customer Support,17,99957,AP008,Active
2,ST0003,Arjun Joseph,Security,Customer Support,19,76035,AP015,On Leave
3,ST0004,Rohan Reddy,Maintenance,Security,16,30662,AP012,Active
4,ST0005,Nisha Singh,Pilot,Flight Operations,15,123352,AP011,On Leave
...,...,...,...,...,...,...,...,...
995,ST0996,Aisha Thomas,Customer Service,Customer Support,16,69431,AP013,Active
996,ST0997,Arjun Singh,Maintenance,Security,16,114570,AP012,Active
997,ST0998,Emma Singh,Security,Cabin Services,17,43271,AP026,Active
998,ST0999,Ananya Wilson,Cabin Crew,Engineering,8,77489,AP029,Active
999,ST1000,Daniel Wilson,Pilot,Engineering,10,117102,AP020,Active

In [96]:
staffs.isnull().sum()

Staff_ID              0
Staff_Name            0
Role                 10
Department           10
Experience_Years      0
Salary_USD            0
Base_Airport_ID       0
Employment_Status     0
dtype: int64

In [97]:
staffs[staffs["Role"].isnull()]

,Staff_ID,Staff_Name,Role,Department,Experience_Years,Salary_USD,Base_Airport_ID,Employment_Status
42,ST0043,Rahul Brown,NaN,Cabin Services,1,70391,AP021,Active
65,ST0066,Karan Thomas,NaN,Management,20,84111,AP003,Active
152,ST0153,Meera Wilson,NaN,Customer Support,20,113802,AP026,Active
277,ST0278,Priya Singh,NaN,Customer Support,10,79624,AP011,Training
367,ST0368,Daniel Patel,NaN,Flight Operations,3,41255,AP018,Active
379,ST0380,Isha Thomas,NaN,Customer Support,21,25280,AP001,Active
577,ST0578,Daniel Joseph,NaN,Ground Operations,25,32024,AP010,Active
597,ST0598,Aarav Sharma,NaN,Customer Support,1,124089,AP012,Active
751,ST0752,Arjun Taylor,NaN,Flight Operations,4,61342,AP021,Training
904,ST0905,Aisha Martin,NaN,Flight Operations,2,41899,AP007,Active

In [98]:
staffs[staffs["Department"].isnull()]

,Staff_ID,Staff_Name,Role,Department,Experience_Years,Salary_USD,Base_Airport_ID,Employment_Status
33,ST0034,Aisha Gupta,Maintenance,NaN,17,52675,AP003,Active
216,ST0217,Nisha Gupta,Ground Staff,NaN,13,58390,AP005,Active
252,ST0253,Olivia Thomas,Maintenance,NaN,24,87068,AP006,On Leave
394,ST0395,Karan Kumar,Security,NaN,22,75445,AP011,Active
555,ST0556,Aditya Martin,Operations,NaN,16,74337,AP027,Active
600,ST0601,Aarav Gupta,Security,NaN,5,100243,AP015,Active
634,ST0635,Kabir Joseph,Maintenance,NaN,9,60802,AP029,Active
699,ST0700,Meera Brown,Operations,NaN,8,96392,AP024,Active
876,ST0877,Vikram Iyer,Security,NaN,24,85798,AP012,Training
916,ST0917,Priya Gupta,Security,NaN,15,44262,AP006,Active

In [99]:
staffs[staffs["Role"].isnull() | staffs["Department"].isnull()]

,Staff_ID,Staff_Name,Role,Department,Experience_Years,Salary_USD,Base_Airport_ID,Employment_Status
33,ST0034,Aisha Gupta,Maintenance,NaN,17,52675,AP003,Active
42,ST0043,Rahul Brown,NaN,Cabin Services,1,70391,AP021,Active
65,ST0066,Karan Thomas,NaN,Management,20,84111,AP003,Active
152,ST0153,Meera Wilson,NaN,Customer Support,20,113802,AP026,Active
216,ST0217,Nisha Gupta,Ground Staff,NaN,13,58390,AP005,Active
252,ST0253,Olivia Thomas,Maintenance,NaN,24,87068,AP006,On Leave
277,ST0278,Priya Singh,NaN,Customer Support,10,79624,AP011,Training
367,ST0368,Daniel Patel,NaN,Flight Operations,3,41255,AP018,Active
379,ST0380,Isha Thomas,NaN,Customer Support,21,25280,AP001,Active
394,ST0395,Karan Kumar,Security,NaN,22,75445,AP011,Active
555,ST0556,Aditya Martin,Operations,NaN,16,74337,AP027,Active
577,ST0578,Daniel Joseph,NaN,Ground Operations,25,32024,AP010,Active
597,ST0598,Aarav Sharma,NaN,Customer Support,1,124089,AP012,Active
600,ST0601,Aarav Gupta,Security,NaN,5,100243,AP015,Active
634,ST0635,Kabir Joseph,Maintenance,NaN,9,60802,AP029,Active
699,ST0700,Meera Brown,Operations,NaN,8,96392,AP024,Active
751,ST0752,Arjun Taylor,NaN,Flight Operations,4,61342,AP021,Training
876,ST0877,Vikram Iyer,Security,NaN,24,85798,AP012,Training
904,ST0905,Aisha Martin,NaN,Flight Operations,2,41899,AP007,Active
916,ST0917,Priya Gupta,Security,NaN,15,44262,AP006,Active

In [100]:
staffs.groupby("Role")["Department"].value_counts()

Role              Department
Cabin Crew        Cabin Services       22
                  Customer Support     22
                  Engineering          21
                  Ground Operations    16
                  Management           15
                  Flight Operations    14
                  Security             10
Co-Pilot          Security             20
                  Flight Operations    20
                  Cabin Services       19
                  Ground Operations    16
                  Customer Support     16
                  Management           14
                  Engineering          12
Customer Service  Engineering          23
                  Cabin Services       22
                  Ground Operations    22
                  Security             18
                  Flight Operations    17
                  Customer Support     15
                  Management            9
Ground Staff      Flight Operations    20
                  Management           19
                  Customer Support     19
                  Engineering          18
                  Ground Operations    14
                  Security             14
                  Cabin Services       12
Maintenance       Customer Support     25
                  Security             21
                  Engineering          19
                  Cabin Services       17
                  Management           17
                  Ground Operations    16
                  Flight Operations    15
Operations        Flight Operations    23
                  Customer Support     20
                  Engineering          15
                  Security             14
                  Management           13
                  Cabin Services       12
                  Ground Operations     5
Pilot             Engineering          27
                  Flight Operations    26
                  Cabin Services       22
                  Customer Support     21
                  Management           20
                  Security             15
                  Ground Operations    14
Security          Flight Operations    21
                  Engineering          19
                  Ground Operations    18
                  Cabin Services       18
                  Security             16
                  Customer Support     16
                  Management           16
Name: count, dtype: int64

In [101]:
staffs.groupby("Department")["Role"].value_counts()

Department         Role
Cabin Services     Pilot               22
                   Cabin Crew          22
                   Customer Service    22
                   Co-Pilot            19
                   Security            18
                   Maintenance         17
                   Ground Staff        12
                   Operations          12
Customer Support   Maintenance         25
                   Cabin Crew          22
                   Pilot               21
                   Operations          20
                   Ground Staff        19
                   Co-Pilot            16
                   Security            16
                   Customer Service    15
Engineering        Pilot               27
                   Customer Service    23
                   Cabin Crew          21
                   Maintenance         19
                   Security            19
                   Ground Staff        18
                   Operations          15
                   Co-Pilot            12
Flight Operations  Pilot               26
                   Operations          23
                   Security            21
                   Ground Staff        20
                   Co-Pilot            20
                   Customer Service    17
                   Maintenance         15
                   Cabin Crew          14
Ground Operations  Customer Service    22
                   Security            18
                   Co-Pilot            16
                   Cabin Crew          16
                   Maintenance         16
                   Pilot               14
                   Ground Staff        14
                   Operations           5
Management         Pilot               20
                   Ground Staff        19
                   Maintenance         17
                   Security            16
                   Cabin Crew          15
                   Co-Pilot            14
                   Operations          13
                   Customer Service     9
Security           Maintenance         21
                   Co-Pilot            20
                   Customer Service    18
                   Security            16
                   Pilot               15
                   Operations          14
                   Ground Staff        14
                   Cabin Crew          10
Name: count, dtype: int64

In [102]:
print("Role mode:", staffs["Role"].mode()[0])
print("Department mode:", staffs["Department"].mode()[0])

Role mode: Pilot
Department mode: Flight Operations

In [103]:
staffs["Role"] = staffs["Role"].fillna(
    staffs["Role"].mode()[0]
)

staffs["Department"] = staffs["Department"].fillna(
    staffs["Department"].mode()[0]
)

In [104]:
staffs.isnull().sum()

Staff_ID             0
Staff_Name           0
Role                 0
Department           0
Experience_Years     0
Salary_USD           0
Base_Airport_ID      0
Employment_Status    0
dtype: int64

In [105]:
aircraft

   Aircraft_ID Airline_ID   Aircraft_Type  Manufacture_Year  Seat_Capacity
0        AC001      AL003     Airbus A350              2009            325
1        AC002      AL003     Airbus A330              2020            300
2        AC003      AL007             NaN              2017            396
3        AC004      AL002     Airbus A320              2024            180
4        AC005      AL004     Airbus A350              2011            325
5        AC006      AL010     Airbus A330              2011            300
6        AC007      AL007     Airbus A330              2019            300
7        AC008      AL002     Airbus A330              2015            300
8        AC009      AL001    Boeing 787-9              2017            296
9        AC010      AL002  Boeing 777-300              2010            396
10       AC011      AL010     Airbus A330              2011            300
11       AC012      AL001  Boeing 737-800              2019            189
12       AC013      AL001     Airbus A350              2011            325
13       AC014      AL010             NaN              2014            325
14       AC015      AL004  Boeing 777-300              2017            396
15       AC016      AL005  Boeing 737-800              2022            189
16       AC017      AL001    Boeing 787-9              2014            296
17       AC018      AL001  Boeing 737-800              2014            189
18       AC019      AL005    Boeing 787-9              2020            296
19       AC020      AL002  Boeing 777-300              2014            396
20       AC021      AL008     Airbus A350              2022            325
21       AC022      AL004     Airbus A330              2018            300
22       AC023      AL003     Airbus A320              2011            180
23       AC024      AL005    Boeing 787-9              2011            296
24       AC025      AL008    Boeing 787-9              2009            296
25       AC026      AL003  Boeing 737-800              2023            189
26       AC027      AL005     Airbus A350              2021            325
27       AC028      AL009    Boeing 787-9              2024            296
28       AC029      AL001     Airbus A321              2013            220
29       AC030      AL008             NaN              2016            325
30       AC031      AL010     Airbus A330              2021            300
31       AC032      AL004  Boeing 777-300              2022            396
32       AC033      AL005     Airbus A321              2023            220
33       AC034      AL007     Airbus A330              2016            300
34       AC035      AL002  Boeing 737-800              2021            189
35       AC036      AL006     Airbus A320              2008            180
36       AC037      AL007     Airbus A321              2011            220
37       AC038      AL003  Boeing 737-800              2009            189
38       AC039      AL002     Airbus A330              2012            300
39       AC040      AL009     Airbus A321              2015            220

In [106]:
aircraft.isnull().sum()

Aircraft_ID         0
Airline_ID          0
Aircraft_Type       3
Manufacture_Year    0
Seat_Capacity       0
dtype: int64

In [107]:
aircraft[aircraft["Aircraft_Type"].isnull()]

   Aircraft_ID Airline_ID Aircraft_Type  Manufacture_Year  Seat_Capacity
2        AC003      AL007           NaN              2017            396
13       AC014      AL010           NaN              2014            325
29       AC030      AL008           NaN              2016            325

In [108]:
aircraft["Aircraft_Type"].value_counts(dropna=False)

Aircraft_Type
Airbus A330       9
Boeing 787-9      6
Boeing 737-800    6
Airbus A350       5
Boeing 777-300    4
Airbus A321       4
NaN               3
Airbus A320       3
Name: count, dtype: int64

In [109]:
aircraft.groupby("Aircraft_Type")["Seat_Capacity"].describe()

                count   mean  std    min    25%    50%    75%    max
Aircraft_Type
Airbus A320       3.0  180.0  0.0  180.0  180.0  180.0  180.0  180.0
Airbus A321       4.0  220.0  0.0  220.0  220.0  220.0  220.0  220.0
Airbus A330       9.0  300.0  0.0  300.0  300.0  300.0  300.0  300.0
Airbus A350       5.0  325.0  0.0  325.0  325.0  325.0  325.0  325.0
Boeing 737-800    6.0  189.0  0.0  189.0  189.0  189.0  189.0  189.0
Boeing 777-300    4.0  396.0  0.0  396.0  396.0  396.0  396.0  396.0
Boeing 787-9      6.0  296.0  0.0  296.0  296.0  296.0  296.0  296.0

In [110]:
aircraft.groupby("Airline_ID")["Aircraft_Type"].value_counts()

Airline_ID  Aircraft_Type
AL001       Boeing 787-9      2
            Boeing 737-800    2
            Airbus A321       1
            Airbus A350       1
AL002       Boeing 777-300    2
            Airbus A330       2
            Airbus A320       1
            Boeing 737-800    1
AL003       Boeing 737-800    2
            Airbus A350       1
            Airbus A330       1
            Airbus A320       1
AL004       Boeing 777-300    2
            Airbus A350       1
            Airbus A330       1
AL005       Boeing 787-9      2
            Airbus A321       1
            Airbus A350       1
            Boeing 737-800    1
AL006       Airbus A320       1
AL007       Airbus A330       2
            Airbus A321       1
AL008       Airbus A350       1
            Boeing 787-9      1
AL009       Boeing 787-9      1
            Airbus A321       1
AL010       Airbus A330       3
Name: count, dtype: int64

In [111]:
capacity_to_type = {
    180: "Airbus A320",
    220: "Airbus A321",
    189: "Boeing 737-800",
    296: "Boeing 787-9",
    300: "Airbus A330",
    325: "Airbus A350",
    396: "Boeing 777-300"
}

aircraft["Aircraft_Type"] = aircraft["Aircraft_Type"].fillna(
    aircraft["Seat_Capacity"].map(capacity_to_type)
)

In [112]:
aircraft.isnull().sum()

Aircraft_ID         0
Airline_ID          0
Aircraft_Type       0
Manufacture_Year    0
Seat_Capacity       0
dtype: int64

In [113]:
flights.columns

Index(['Flight_ID', 'Flight_Date', 'Airline_ID', 'Aircraft_ID',
       'Origin_Airport_ID', 'Destination_Airport_ID', 'Scheduled_Departure',
       'Actual_Departure', 'Delay_Minutes', 'Delay_Reason', 'Status',
       'Flight_Duration_Min', 'Distance_KM', 'Seat_Capacity', 'Passengers',
       'Base_Fare_USD', 'Revenue_USD', 'Load_Factor_%', 'Season'],
      dtype='str')

In [114]:
print("Flights:")
print(flights.isnull().sum())

print("\nPassengers:")
print(passengers.isnull().sum())

print("\nRoutes:")
print(routes.isnull().sum())

print("\nAirlines:")
print(airlines.isnull().sum())

print("\nAirports:")
print(airports.isnull().sum())

print("\nStaffs:")
print(staffs.isnull().sum())

print("\nAircraft:")
print(aircraft.isnull().sum())

Flights:
Flight_ID                 0
Flight_Date               0
Airline_ID                0
Aircraft_ID               0
Origin_Airport_ID         0
Destination_Airport_ID    0
Scheduled_Departure       0
Actual_Departure          0
Delay_Minutes             0
Delay_Reason              0
Status                    0
Flight_Duration_Min       0
Distance_KM               0
Seat_Capacity             0
Passengers                0
Base_Fare_USD             0
Revenue_USD               0
Load_Factor_%             0
Season                    0
dtype: int64

Passengers:
Passenger_ID          0
Passenger_Name        0
Age                   0
Gender                0
Nationality           0
Travel_Class          0
Flight_ID             0
Booking_Channel       0
Ticket_Price_USD      0
Satisfaction_Score    0
Satisfaction_Level    0
dtype: int64

Routes:
Origin_Airport_ID           0
Destination_Airport_ID      0
Flights                     0
Total_Passengers            0
Total_Revenue_USD           0
Avg_Load_Factor_Pct         0
Avg_Delay_Minutes           0
Route_ID                    0
Origin_City                58
Destination_City           57
Route_Name                113
dtype: int64

Airlines:
Airline_ID      0
Airline_Name    0
Country         1
dtype: int64

Airports:
Airport_ID      0
Airport_Name    0
City            0
Country         0
IATA_Code       0
Latitude        0
Longitude       0
dtype: int64

Staffs:
Staff_ID             0
Staff_Name           0
Role                 0
Department           0
Experience_Years     0
Salary_USD           0
Base_Airport_ID      0
Employment_Status    0
dtype: int64

Aircraft:
Aircraft_ID         0
Airline_ID          0
Aircraft_Type       0
Manufacture_Year    0
Seat_Capacity       0
dtype: int64

In [152]:
flights.to_csv("flights_cleaned.csv", index=False)
passengers.to_csv("passengers_cleaned.csv", index=False)
routes.to_csv("routes_cleaned.csv", index=False)
airlines.to_csv("airlines_cleaned.csv", index=False)
airports.to_csv("airports_cleaned.csv", index=False)
staffs.to_csv("staffs_cleaned.csv", index=False)
aircraft.to_csv("aircraft_cleaned.csv", index=False)

In [116]:
import os

print(os.getcwd())

C:\Users\Asus

In [117]:
check_flights = pd.read_csv("flights_cleaned.csv")
check_flights.head()

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
0,FL00001,2023-03-02,AL002,AC013,AP013,AP027,2023-03-02 15:00:00,2023-03-02 15:11:00,11.0,Security,Delayed,647,1322,325,219,361.0,79059,67.384615,Spring
1,FL00002,2023-11-18,AL009,AC036,AP010,AP006,2023-11-18 22:30:00,2023-11-18 22:36:00,6.0,Technical,Delayed,603,5627,180,131,624.0,81744,72.777778,Autumn
2,FL00003,2025-02-05,AL002,AC019,AP022,AP009,2025-02-05 19:30:00,2025-02-05 19:30:00,0.0,No Delay,On Time,262,2326,296,225,541.0,121725,76.013514,Winter
3,FL00004,2023-11-20,AL004,AC012,AP024,AP030,2023-11-20 13:00:00,2023-11-20 13:12:00,12.0,Late Aircraft,Delayed,354,1407,189,163,469.0,76447,86.243386,Autumn
4,FL00005,2025-03-30,AL003,AC023,AP023,AP016,2025-03-30 08:15:00,2025-03-30 08:25:00,10.0,Late Aircraft,Delayed,207,2646,180,178,214.0,38092,98.888889,Spring

In [118]:
print(check_flights.columns.tolist())

['Flight_ID', 'Flight_Date', 'Airline_ID', 'Aircraft_ID', 'Origin_Airport_ID', 'Destination_Airport_ID', 'Scheduled_Departure', 'Actual_Departure', 'Delay_Minutes', 'Delay_Reason', 'Status', 'Flight_Duration_Min', 'Distance_KM', 'Seat_Capacity', 'Passengers', 'Base_Fare_USD', 'Revenue_USD', 'Load_Factor_%', 'Season']

In [161]:
flights.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/flights_cleaned.csv", index=False)
passengers.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/passengers_cleaned.csv", index=False)
routes.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/routes_cleaned.csv", index=False, encoding="utf-8-sig")
airlines.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/airlines_cleaned.csv", index=False)
airports.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/airports_cleaned.csv", index=False)
staffs.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/staffs_cleaned.csv", index=False)
aircraft.to_csv(r"C:\Users\Asus\Downloads\airline_cleaned/aircraft_cleaned.csv", index=False)

In [162]:
flights1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/flights_cleaned.csv")
passengers1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned\passengers_cleaned.csv")
routes1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/routes_cleaned.csv")
airlines1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/airlines_cleaned.csv")
airports1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/airports_cleaned.csv")
aircraft1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/aircraft_cleaned.csv")
staffs1=pd.read_csv(r"C:\Users\Asus\Downloads\airline_cleaned/staffs_cleaned.csv")
flights1

,Flight_ID,Flight_Date,Airline_ID,Aircraft_ID,Origin_Airport_ID,Destination_Airport_ID,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason,Status,Flight_Duration_Min,Distance_KM,Seat_Capacity,Passengers,Base_Fare_USD,Revenue_USD,Load_Factor_%,Season
0,FL00001,2023-03-02,AL002,AC013,AP013,AP027,2023-03-02 15:00:00,2023-03-02 15:11:00,11.0,Security,Delayed,647,1322,325,219,361.0,79059,67.384615,Spring
1,FL00002,2023-11-18,AL009,AC036,AP010,AP006,2023-11-18 22:30:00,2023-11-18 22:36:00,6.0,Technical,Delayed,603,5627,180,131,624.0,81744,72.777778,Autumn
2,FL00003,2025-02-05,AL002,AC019,AP022,AP009,2025-02-05 19:30:00,2025-02-05 19:30:00,0.0,No Delay,On Time,262,2326,296,225,541.0,121725,76.013514,Winter
3,FL00004,2023-11-20,AL004,AC012,AP024,AP030,2023-11-20 13:00:00,2023-11-20 13:12:00,12.0,Late Aircraft,Delayed,354,1407,189,163,469.0,76447,86.243386,Autumn
4,FL00005,2025-03-30,AL003,AC023,AP023,AP016,2025-03-30 08:15:00,2025-03-30 08:25:00,10.0,Late Aircraft,Delayed,207,2646,180,178,214.0,38092,98.888889,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,FL04996,2024-05-13,AL009,AC019,AP004,AP024,2024-05-13 08:30:00,2024-05-13 10:51:00,141.0,Air Traffic,Severely Delayed,557,4912,296,211,533.0,112463,71.283784,Spring
4996,FL04997,2023-05-19,AL002,AC036,AP017,AP009,2023-05-19 11:45:00,2023-05-19 12:00:00,15.0,Weather,Delayed,492,3561,180,131,279.0,36549,72.777778,Spring
4997,FL04998,2023-11-27,AL002,AC011,AP024,AP015,2023-11-27 17:15:00,2023-11-27 17:17:00,2.0,Air Traffic,Delayed,291,1483,300,288,396.0,114048,96.000000,Autumn
4998,FL04999,2025-02-13,AL008,AC039,AP018,AP013,2025-02-13 14:15:00,2025-02-13 14:21:00,6.0,Late Aircraft,Delayed,326,3218,300,227,496.0,112592,75.666667,Winter
4999,FL05000,2023-10-17,AL008,AC036,AP004,AP018,2023-10-17 13:00:00,2023-10-17 13:02:00,2.0,Crew,Delayed,465,3254,180,103,185.0,19055,57.222222,Autumn